### PR TITLE
[Rust] Allow resuming a session that was killed with ctrl + c

### LINKED ISSUE #1244: Hitting Ctrl+C once should interrupt the model and give you a chance to redirect it
Currently, hitting `Ctrl+C` interrupts the model in the Rust TUI, but if you submit another message, the model is generally confused and you cannot actually continue your conversation with new instructions. I believe this is because there is almost always inevitably a tool call outstanding when this happens and when the user hits `Ctrl+C`, we just fail to respond.

I believe this is because we need to respond with `"aborted"` along the lines of:

https://github.com/openai/codex/blob/029f39b9da894d27dcde81b8636ef89d8b652a9f/codex-cli/src/utils/agent/handle-exec-command.ts#L363-L373

so that the model has a response to the tool call, after which it will consider the next user message.

/cc @fouad-openai to confirm this

See also: https://github.com/openai/codex/issues/1245.

### PR DESCRIPTION
**Pull request by gpeal**
Previously, if you ctrl+c'd a conversation, all subsequent turns would 400 because the Responses API never got a response for one of its call ids. This ensures that if we aren't sending a call id by hand, we generate a synthetic aborted call.

Fixes #1244 

https://github.com/user-attachments/assets/5126354f-b970-45f5-8c65-f811bca8294a

### CODE REVIEW

File: codex-rs/core/src/client.rs [hunk 1]
```diff
@@ -296,6 +299,11 @@ where
                     return;
                 }
             }
+            "response.created" => {
+                if let Some(_) = event.response {
```
Comment (bolinfest) [inline codex-rs/core/src/client.rs]: I predict Clippy wants `if event.response.is_some()`?

I have this in my `settings.json` in VS Code:

```
  "rust-analyzer.check.command": "clippy",
  "rust-analyzer.check.extraArgs": ["--", "-D", "warnings"],
```

File: codex-rs/core/src/client_common.rs [hunk 2]
```diff
@@ -50,6 +50,7 @@ impl Prompt {
 
 #[derive(Debug)]
 pub enum ResponseEvent {
+    Created {},
```
Comment (bolinfest) [inline codex-rs/core/src/client_common.rs]:
```suggestion
    Created,
```

File: codex-rs/core/src/codex.rs [hunk 3]
```diff
@@ -1062,7 +1068,59 @@ async fn try_run_turn(
...
+                call_id: call_id.clone(),
+                output: FunctionCallOutputPayload {
+                    content: "aborted".to_string(),
+                    success: Some(false),
+                },
+            })
+            .collect::<Vec<_>>()
+    };
+    let prompt = if missing_calls.is_empty() {
+        prompt.clone()
```
Comment (bolinfest) [inline codex-rs/core/src/codex.rs]: I think you want `let prompt: Cow<'a, Prompt>` if you can to avoid the `clone()`? So in the consequent, it's `Cow::Borrowed` and in the alternative, it's `Cow::Owned`?

File: codex-rs/core/src/codex.rs [hunk 4]
```diff
@@ -1062,7 +1068,59 @@ async fn try_run_turn(
...
+            .map(|call_id| ResponseItem::FunctionCallOutput {
+                call_id: call_id.clone(),
+                output: FunctionCallOutputPayload {
+                    content: "aborted".to_string(),
+                    success: Some(false),
+                },
+            })
+            .collect::<Vec<_>>()
+    };
+    let prompt = if missing_calls.is_empty() {
```
Comment (bolinfest) [inline codex-rs/core/src/codex.rs]: Can you add a comment explaining why we redefine the prompt when `missing_calls` is non-empty?

File: codex-rs/core/src/codex.rs [hunk 5]
```diff
@@ -1062,7 +1068,59 @@ async fn try_run_turn(
...
+        prompt.clone()
+    } else {
+        let input = [prompt.input.clone(), missing_calls].concat();
+        Prompt {
+            input,
+            prev_id: prompt.prev_id.clone(),
+            user_instructions: prompt.user_instructions.clone(),
+            store: prompt.store,
+            extra_tools: prompt.extra_tools.clone(),
+        }
```
Comment (bolinfest) [inline codex-rs/core/src/codex.rs]: Does this work?

```suggestion
        Prompt {
            input: [prompt.input.clone(), missing_calls].concat(),
            ..prompt.clone(),
        }
```

**Review by bolinfest — APPROVED** [review]
Generally looks good, though please check CI failures!
