### PR TITLE
Fix wayland image paste error

### LINKED ISSUE #4818: Ctrl+V image paste shows no placeholder on Wayland despite successful clipboard read
## Problem
In the TUI, pressing `Ctrl+V` after copying a PNG succeeds according to the
`paste_image_as_png` span, yet the composer never shows the `[image …]` placeholder and no
image is attached. There’s also no user-visible error.

## Steps to Reproduce
1. Launch Codex TUI on a native Wayland terminal (`kitty` Wayland backend).
2. Copy a PNG (I used a fresh screenshot).
3. Focus the composer and press `Ctrl+V`.
4. Observe that nothing appears; retrying yields the same result.

## Expected
An image placeholder should appear in the composer, just as it does on X11 terminals.

## Actual
The log shows the clipboard read finishing successfully, yet the composer stays unchanged
and no `attach_image` entries appear. Because the `Ctrl+V` handler ignores the `Err` from
`paste_image_to_temp_png()`, any failure in that helper is swallowed, leaving the paste
as a silent no-op. Please add Wayland-safe image paste support and surface the failure so
users know what happened.

## Silent error
The `Ctrl+V` handler in `codex-rs/tui/src/chatwidget.rs:1015-1035` calls
`paste_image_to_temp_png()` inside `if let Ok((path, info)) = paste_image_to_temp_png()`.
Because the `Err` branch is never matched, any failure immediately exits the handler
without logging or UI feedback. The helper (`codex-rs/tui/src/clipboard_paste.rs:121-135`)
does return detailed `PasteImageError::IoError/NoImage/...`, but since the caller ignores
the `Err`, those messages never reach the log or the user, so the paste simply appears to
do nothing.

```rust
// codex-rs/tui/src/chatwidget.rs:1015-1035
KeyEvent {
        code: KeyCode::Char('v'),
        modifiers: KeyModifiers::CONTROL,
        kind: KeyEventKind::Press,
        ..
} => {
  if let Ok((path, info)) = paste_image_to_temp_png() {
    self.attach_image(path, info.width, info.height, info.encoded_format.label());
  }
  return;
}
```

`paste_image_to_temp_png()` returns a `Result`, but only the `Ok` branch is handled. Any `Err`
immediately returns from `handle_key_event` with no log or UI feedback.

```rust
// codex-rs/tui/src/clipboard_paste.rs:121-134
pub fn paste_image_to_temp_png() -> Result<(PathBuf, PastedImageInfo), PasteImageError> {
  let (png, info) = paste_image_as_png()?;
  let tmp = Builder::new()
    .prefix("codex-clipboard-")
    .suffix(".png")
    .tempfile()
    .map_err(|e| PasteImageError::IoError(e.to_string()))?;
  std::fs::write(tmp.path(), &png).map_err(|e| PasteImageError::IoError(e.to_string()))?;
  let (_file, path) = tmp
    .keep()
    .map_err(|e| PasteImageError::IoError(e.error.to_string()))?;
  Ok((path, info))
}
```

The helper maps failures to `PasteImageError`, but because the caller discards
the `Err` branch, every error path becomes a silent no-op, so nothing reaches the logs or
the user.

### Additional information

- Codex CLI: 0.44.0
- OS: Arch Linux (Wayland session; DISPLAY=:0, WAYLAND_DISPLAY=wayland-1)
- Terminal: kitty 0.43.1 (Wayland backend)
- TMPDIR: /tmp (default)
- Repro: copy a PNG screenshot → focus Codex → press Ctrl+V → nothing appears
- Log snippet (ANSI stripped):
  2025-10-06T11:11:43.261773Z DEBUG paste_image_as_png: attempting clipboard image read
  2025-10-06T11:11:43.263943Z DEBUG paste_image_as_png:get_image: close time.busy=505µs time.idle=11.1µs
  2025-10-06T11:11:43.264248Z DEBUG paste_image_as_png: close time.busy=2.47ms time.idle=9.65µs
  - Note: no subsequent `attach_image` or `PasteImageError` entries appear in `~/.codex/log/codex-tui.log`.

### PR DESCRIPTION
**Pull request by MasterMind7777777**
## Summary
  - log and surface clipboard failures instead of silently ignoring them when `Ctrl+V` pastes an image (`paste_image_to_temp_png()` now feeds an error history cell)
  - enable `arboard`’s `wayland-data-control` feature so native Wayland sessions can deliver image data without XWayland
  - keep the success path unchanged: valid images still attach and show the `[image …]` placeholder as before

Fixes #4818

### CODE REVIEW

**Comment by MasterMind7777777** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by MasterMind7777777** [comment]
rebased to new main

**Comment by etraut-openai** [comment]
Thanks for the contribution, and apologies for the slow reply. We received many PRs, and we're just now catching up on the backlog.

I took a quick look at your PR. The code change in `chatwidget.rs` looks reasonable to me, but I don't understand why it includes changes to the `Cargo.lock` or `Cargo.toml` files. Please simplify the change.

**Comment by etraut-openai** [comment]
codex review

**Comment by MasterMind7777777** [comment]
Change to Cargo.toml is most important, that is what actually fixes issue that paste image does not work on Wayland, it does not work because dependency(feature) that handles Wayland specific clipboard was not included before. 

Change in chatwidget.rs only logs error if something else breaks in image pasting, so in future it would be easier to debug. It does not actually fix anything. 

All that needs to be done to be able to do paste image on Wayland is 
wayland-data-control feature need to be enabled for lib arboard in Cargo.toml

**Comment by etraut-openai** [comment]
Thanks for the explanation. I didn't previously understand that `wayland-data-control` was an optional feature in `arboard`. Makes sense now.

File: codex-rs/tui/src/chatwidget.rs [hunk 1]
```diff
@@ -1143,8 +1143,22 @@ impl ChatWidget {
...
+                            info.height,
+                            info.encoded_format.label(),
+                        );
+                    }
+                    Err(err) => {
+                        tracing::warn!("failed to paste image: {err}");
+                        self.add_to_history(history_cell::new_error_event(format!(
+                            "Failed to paste image: {err}",
+                        )));
+                        self.request_redraw();
```
Comment (nornagon-openai) [inline codex-rs/tui/src/chatwidget.rs]: I don't believe `request_redraw()` is needed here.

**Review by nornagon-openai — APPROVED** [review]

File: codex-rs/tui/src/chatwidget.rs (hunk 1 above)
Comment (nornagon-openai) [inline codex-rs/tui/src/chatwidget.rs]:
```suggestion
```
