### PR TITLE
fix: resolve Windows MCP server execution for script-based tools

### LINKED ISSUE #2945: MCP client for `playwright` failed to start: program not found
### What version of Codex is running?

codex-cli 0.25.0

### Which model were you using?

gpt-5 medium

### What platform is your computer?

Windows 11 (Microsoft Windows NT 10.0.26100.0 x64 )

### What steps can reproduce the bug?

1. Install like on the Dexcription here: https://github.com/microsoft/playwright-mcp
2. Run Codex it rteunrs   `MCP client for `playwright` failed to start: program not found  `

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by 25621**
## What?

Fixes MCP server initialization failures on Windows when using script-based tools like `npx`, `pnpm`, and `yarn` that rely on `.cmd`/`.bat` files rather than `.exe` binaries.

Fixes #2945

## Why?

Windows users encounter "program not found" errors when configuring MCP servers with commands like `npx` in their `~/.codex/config.toml`. This happens because:

- Tools like `npx` are batch scripts (`npx.cmd`) on Windows, not executable binaries
- Rust's `std::process::Command` bypasses the shell and cannot execute these scripts directly
- The Windows shell normally handles this by checking `PATHEXT` for executable extensions

Without this fix, Windows users must specify full paths or add `.cmd` extensions manually, which breaks cross-platform compatibility.

## How?

Added platform-specific program resolution using the `which` crate to find the correct executable path:

- **Windows**: Resolves programs through PATH/PATHEXT to find `.cmd`/`.bat` scripts
- **Unix**: Returns the program unchanged (no-op, as Unix handles scripts natively)

### Changes

- Added `which = "6"` dependency to `mcp-client/Cargo.toml`
- Implemented `program_resolver` module in `mcp_client.rs` with platform-specific resolution
- Added comprehensive tests for both Windows and Unix behavior

### Testing

Added platform-specific tests to verify:
- Unix systems execute scripts without extensions
- Windows fails without proper extensions
- Windows succeeds with explicit extensions
- Cross-platform resolution enables successful execution

**Tested on:**
- Windows 11 (NT 10.0.26100.0 x64)
- PowerShell 5.1 & 7+, CMD, Git Bash
- MCP servers: playwright, context7, supabase
- WSL (verified no regression)

**Local checks passed:**
```bash
cargo test && cargo clippy --tests && cargo fmt -- --config imports_granularity=Item
```

### Results

**Before:**
```
🖐 MCP client for `playwright` failed to start: program not found
```

**After:**
```
🖐 MCP client for `playwright` failed to start: request timed out
```

Windows users can now use simple commands like `npx` in their config without specifying full paths or extensions. The timeout issue is a separate concern that will be addressed in a follow-up PR.

### CODE REVIEW

**Comment by 25621** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by etraut-openai** [comment]
Thanks for the contribution, and apologies for the slow response. We received a large number of PRs, and we're just now getting through the backlog.

It looks like this PR has gone stale. If this PR is still relevant, could you please resolve the merge conflicts and make sure the tests still run? Thanks!

**Comment by 25621** [comment]
Hi @etraut-openai,

Thank you for reviewing! I've resolved the conflicts and updated the PR:

- ✅ Rebased on latest main
- ✅ Applied fix to `rmcp-client` (which replaced `mcp-client` in #5529)
- ✅ Verified issue #2945 still reproduces on v0.55.0 and main
- ✅ All tests pass: `cargo test -p codex-rmcp-client`

The Windows script resolution logic remains unchanged - using the `which` crate to properly resolve .cmd/.bat scripts that Windows requires for tools like npx, pnpm, and yarn.

Ready for merge. Let me know if you need any adjustments!

**Comment by etraut-openai** [comment]
@25621, looks like there are some lint (`cargo clippy`) issues remaining.

**Comment by 25621** [comment]
@etraut-openai Fixed! Thanks for catching that.

**Issue:** The `tracing::debug` import was only used in Windows-specific code but included on all platforms.

**Fix:** Wrapped the import with `#[cfg(windows)]` to match its usage scope.

**Verification:**
* ✅ `cargo clippy -p codex-rmcp-client --tests` - no warnings
* ✅ `cargo test -p codex-rmcp-client` - all tests pass

The workflows are awaiting maintainer approval to run. Would appreciate if you could approve them when you get a chance. Thanks!

File: codex-rs/rmcp-client/src/rmcp_client.rs [hunk 1]
```diff
@@ -412,3 +419,214 @@ async fn create_oauth_transport_and_runtime(
...
+        }
+    }
+
+    /// Unix systems handle PATH resolution natively.
+    ///
+    /// The OS can execute scripts directly, so no resolution needed.
+    #[cfg(unix)]
+    pub fn resolve(program: OsString, _env: &HashMap<String, String>) -> std::io::Result<OsString> {
+        Ok(program)
+    }
```
Comment (dylan-hurd-oai) [inline codex-rs/rmcp-client/src/rmcp_client.rs]: nit: can we move this one to be first? It's simpler / shorter.

File: codex-rs/rmcp-client/src/rmcp_client.rs [hunk 2]
```diff
@@ -412,3 +419,214 @@ async fn create_oauth_transport_and_runtime(
 
     Ok((transport, runtime))
 }
+
+/// Platform-specific program resolution for MCP server execution.
+///
+/// Resolves executable paths differently based on the operating system:
+/// - **Windows**: Uses `which` crate to find executables including scripts (.cmd, .bat)
+/// - **Unix**: Returns the program unchanged (native PATH resolution handles it)
+mod program_resolver {
```
Comment (dylan-hurd-oai) [inline codex-rs/rmcp-client/src/rmcp_client.rs]: If we're going to create a separate mod, let's put it in a different file, please

**Review by dylan-hurd-oai — COMMENTED** [review]
Thanks for the contribution! 2 small organizational comments to address, but overall this looks good to me

**Comment by 25621** [comment]
@dylan-hurd-oai Thanks for the review! I've addressed both comments:

1. ✅ **Reordered functions**: Moved the Unix implementation first as it's simpler/shorter
2. ✅ **Extracted to separate file**: Created `src/program_resolver.rs` with the module and its tests

The tests are now co-located with the module they're testing for better maintainability. All existing functionality remains unchanged - this is purely a refactoring for better code organization.

Ready for another review!

**Comment by dylan-hurd-oai** [comment]
Noting that I've tested this on a Windows device as well. Thanks for the fix! cc @gpeal for mcp visibility.

**Review by dylan-hurd-oai — APPROVED** [review]
