### PR TITLE
LM Studio OSS Support

### LINKED ISSUE #1883: LM Studio OSS
### What is the type of issue?

Documentation is missing

### What is the issue?

I was unable to get codex to connect with lm studio.

export CODEX_OSS_BASE_URL="http://localhost:1234/v1"

codex --oss -m "openai/gpt-oss-20b"

LM studio sees the connection attempt but it fails. 

Pulling model openai/gpt-oss-20b...Error: OSS setup failed: Pull stream ended unexpectedly without success.

Asking chatgpt for assistance, it had me adjusting config.toml and no luck neither. 

### Where did you find it?

_No response_

### PR DESCRIPTION
**Pull request by rugvedS07**
## Overview

Adds LM Studio OSS support. Closes #1883

### Changes
This PR enhances the behavior of `--oss` flag to support LM Studio as a provider. Additionally, it introduces a new flag`--local-provider` which can take in `lmstudio` or `ollama` as values if the user wants to explicitly choose which one to use.

If no provider is specified `codex --oss` will auto-select the provider based on whichever is running.

#### Additional enhancements 
The default can be set using `oss-provider` in config like:

```
oss_provider = "lmstudio"
```

For non-interactive users, they will need to either provide the provider as an arg or have it in their `config.toml`

### Notes
For best performance, [set the default context length](https://lmstudio.ai/docs/app/advanced/per-model) for gpt-oss to the maximum your machine can support

### CODE REVIEW

**Comment by rugvedS07** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by DocMAX** [comment]
please merge asap, thanks!

**Comment by dkundel-openai** [comment]
@codex review

File: codex-rs/tui/src/oss_selection.rs [hunk 1]
```diff
@@ -0,0 +1,369 @@
...
+        .timeout(Duration::from_secs(2))
+        .build()
+        .map_err(io::Error::other)?;
+
+    let url = format!("http://localhost:{port}");
+
+    match client.get(&url).send().await {
+        Ok(response) => Ok(response.status().is_success()),
+        Err(_) => Ok(false), // Connection failed = not running
+    }
```
[the remark this answers is not in the document]
Comment (rugvedS07) [reply codex-rs/tui/src/oss_selection.rs:368]: Ollama and LM Studio both return `200` when either server is healthy

**Comment by mattjcly** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by yagil** [comment]
Hey @easong-openai @aibrahim-oai we recently added `/v1/responses` compatibility support (see [tweet](https://x.com/lmstudio/status/1975300430960992523)) and updated this PR to use it. Would be really awesome and appreciated for it to be reviewed by y'all! 🙏 Cheers (cc @dkundel-openai)

**Comment by Bauvater** [comment]
pls update it

**Comment by etraut-openai** [comment]
Thanks for the contribution, and apologies for the slow response. We had a large number of PRs submitted, and we're just now digging out from our backlog. 

If you're still interested in pursuing this PR, could you please resolve the merge conflicts?

**Comment by rugvedS07** [comment]
> Thanks for the contribution, and apologies for the slow response. We had a large number of PRs submitted, and we're just now digging out from our backlog.
> 
> If you're still interested in pursuing this PR, could you please resolve the merge conflicts?

Hello, no issues. I just fixed the conflicts, should be conflict free and good to review!

**Comment by yagil** [comment]
Thanks @etraut-openai. Confirming we are still interested in pursuing the PR

File: codex-rs/lmstudio/src/client.rs [hunk 2]
```diff
@@ -0,0 +1,397 @@
...
+use std::io;
+use std::path::Path;
+
+#[derive(Clone)]
+pub struct LMStudioClient {
+    client: reqwest::Client,
+    base_url: String,
+}
+
+const LMSTUDIO_CONNECTION_ERROR: &str = "Can't reach LM Studio. Is it running with the server on?  If you don't have it yet, try to run `lms server start` after installation https://lmstudio.ai/download";
```
Comment (etraut-openai) [inline codex-rs/lmstudio/src/client.rs]: Nit: Double space between sentences should be single space.

Error message is a bit cumbersome. Suggestion: "LM Studio is not responding. Install from https://lmstudio.ai/download and run 'lms server start'."

File: codex-rs/tui/src/lib.rs [hunk 3]
```diff
@@ -124,21 +129,103 @@ pub async fn run_main(
...
+            Ok(config_toml) => config_toml,
+            Err(err) => {
+                eprintln!("Error loading config.toml: {err}");
+                std::process::exit(1);
+            }
+        };
+
     let model_provider_override = if cli.oss {
-        Some(BUILT_IN_OSS_MODEL_PROVIDER_ID.to_owned())
+        if let Some(provider) = &cli.oss_provider {
```
Comment (etraut-openai) [inline codex-rs/tui/src/lib.rs]: This logic is largely duplicated between the tui and exec crates. The only difference is that the tui version falls back to an interactive menu. This duplication will create maintenance issues because override logic will need to be kept in sync between the two places. This logic should be unified in the config crate so it's implemented only once.

File: codex-rs/tui/src/lib.rs [hunk 4]
```diff
@@ -124,21 +129,103 @@ pub async fn run_main(
...
+                }
+                Some(provider)
+            }
+        }
     } else {
         None
     };
 
+    // When using `--oss`, let the bootstrapper pick the model based on selected provider
+    let model = if let Some(model) = &cli.model {
```
Comment (etraut-openai) [inline codex-rs/tui/src/lib.rs]: This logic is also duplicated. Look for ways to consolidate.

**Review by etraut-openai — CHANGES_REQUESTED** [review]
Overall, this looks good to me. I left a few suggestions.

In addition to reviewing the code, I also did some manual testing and confirmed that it works as advertised with both LM Studio and Ollama config setts.

**Review by etraut-openai — APPROVED** [review]
