### PR TITLE
fix: allow continuing after interrupting assistant

### LINKED ISSUE #114: Unable to continue after hitting esc esc to interrupt assistant
after interrupting, it's not possible to continue usage without clearing the history. Subsequent messages consistently yield errors like:
```
⚠️  OpenAI rejected the request (request ID:
    req_***). Please verify your
    settings and try again.
```

### PR DESCRIPTION
**Pull request by binbandit**
## Description
This PR fixes the issue where the CLI can't continue after interrupting the assistant with ESC ESC (Fixes #114). The problem was caused by duplicate code in the `cancel()` method and improper state reset after cancellation.

## Changes
- Fixed duplicate code in the `cancel()` method of the `AgentLoop` class
- Added proper reset of the `currentStream` property in the `cancel()` method
- Created a new `AbortController` after aborting the current one to ensure future tool calls work
- Added a system message to indicate the interruption to the user
- Added a comprehensive test to verify the fix

## Benefits
- Users can now continue using the CLI after interrupting the assistant
- Improved user experience by providing feedback when interruption occurs
- Better state management in the agent loop

## Testing
- Added a dedicated test that verifies the agent can process new input after cancellation
- Manually tested the fix by interrupting the assistant and confirming that new input is processed correctly

### CODE REVIEW

File: codex-cli/src/utils/agent/agent-loop.ts [hunk 1]
```diff
@@ -138,23 +146,6 @@ export class AgentLoop {
...
-    // NOTE: We intentionally do *not* clear `lastResponseId` here.  If the
-    // stream produced a `function_call` before the user cancelled, OpenAI now
-    // expects a corresponding `function_call_output` that must reference that
-    // very same response ID.  We therefore keep the ID around so the
-    // follow‑up request can still satisfy the contract.
-
-    // If we have *not* seen any function_call IDs yet there is nothing that
-    // needs to be satisfied in a follow‑up request.  In that case we clear
-    // the stored lastResponseId so a subsequent run starts a clean turn.
-    if (this.pendingAborts.size === 0) {
```
Comment (tibo-openai) [inline codex-cli/src/utils/agent/agent-loop.ts]: What is the rationale for removing this logic?

Comment (binbandit) [reply codex-cli/src/utils/agent/agent-loop.ts]: I removed the duplicate logic that was present

**Comment by tibo-openai** [comment]
merged, ty!
