### PR TITLE
fix(linux-sandbox): mount /dev in bwrap sandbox

### LINKED ISSUE #12056: Allow access of `/dev/urandom` from bubblewrap sandbox
### What version of Codex CLI is running?

built from `main` (a1b8e34938a26b3910de2abdb2e984aa12624354)

### What subscription do you have?

Plus

### Which model were you using?

gpt-5.3-codex

### What platform is your computer?

Linux 4.18.0-553.77.1.el8_10.x86_64 x86_64 x86_64

### What terminal emulator and version are you using (if applicable)?

_No response_

### What issue are you seeing?

I'm trying the experimental feature `bubblewrap` as the sandbox option. This is because `landlock` is not available on my kernel. So far this feature looks good to me with some slight issues.

When a sandbox command needs to read from `/dev/urandom`, it fails.

Some commands (like git) requires secure random number from that device.

I'm building codex directly from `main`.

### What steps can reproduce the bug?

Set the following in config:
```
features.use_linux_sandbox_bwrap = true
sandbox_mode = "workspace-write"
approval_policy = "never"
```

Tell agent:
```
try to read from `/dev/urandom`
```

Agent ran:
```
head -c 16 /dev/urandom | od -An -tx1
```

Command failed with:
```
head: cannot open '/dev/urandom' for reading: Permission denied
```

### What is the expected behavior?

Agent successfully reads from secure random.

### Additional information

The error is weird because root is bind read-only while it looks like reading `/dev/urandom` requires full permission.

I read through the current sandbox code (`linux-sandbox/src/bwrap.rs`). Currently it only adds `--dev-bind /dev/null /dev/null`. Consider to add other bindings (`/dev/urandom`, `/dev/zero`, etc.) or maybe use bubblewrap's `--dev /dev` option (not sure if it works with read-only root binding though).

### PR DESCRIPTION
**Pull request by viyatb-oai**
## Summary
- Updates the Linux bubblewrap sandbox args to mount a minimal `/dev` using `--dev /dev` instead of only binding `/dev/null`. tools needing entropy (git, crypto libs, etc.) can fail.

- Changed mount order so `--dev /dev` is added before writable-root `--bind` mounts, preserving writable `/dev/*` submounts like `/dev/shm`

## Why
Fixes sandboxed command failures when reading `/dev/urandom` (and similar standard device-node access).

Fixes https://github.com/openai/codex/issues/12056

### CODE REVIEW

File: codex-rs/linux-sandbox/src/linux_run_main.rs [hunk 1]
```diff
@@ -148,13 +148,22 @@ fn run_bwrap_with_proc_fallback(
...
     }
 
-    let network_mode = bwrap_network_mode(sandbox_policy, allow_network_for_proxy);
+    if network_mode != BwrapNetworkMode::FullAccess
+        && !preflight_unshare_net_support(sandbox_policy_cwd, sandbox_policy, mount_proc)
+    {
+        eprintln!(
+            "codex-linux-sandbox: bwrap could not configure loopback in a network namespace; retrying without --unshare-net"
+        );
+        network_mode = BwrapNetworkMode::FullAccess;
```
Comment (bolinfest) [inline codex-rs/linux-sandbox/src/linux_run_main.rs]: Is this meant to be part of this PR? I don't think we should be silently upgrading to `FullAccess` for `network_mode`: we should just fail?

File: codex-rs/linux-sandbox/src/bwrap.rs
Comment (bolinfest) [inline codex-rs/linux-sandbox/src/bwrap.rs:196]: Why is this inside this loop?

File: codex-rs/linux-sandbox/src/bwrap.rs [hunk 2]
```diff
@@ -368,4 +369,80 @@ mod tests {
             ]
         );
     }
+
+    #[test]
```
Comment (bolinfest) [inline codex-rs/linux-sandbox/src/bwrap.rs]: What I would really like to see are integration tests rather than unit tests.

File: codex-rs/linux-sandbox/src/bwrap.rs
Comment (viyatb-oai) [reply codex-rs/linux-sandbox/src/bwrap.rs:196]: For each read-only path, this is adding its own `--ro-bind ...` protection.
```
--ro-bind /dev/null /repo/.git
--ro-bind /dev/null /repo/.codex
```

**Review by bolinfest — APPROVED** [review]
