### PR TITLE
Deduplicate MCP tool names

### LINKED ISSUE #1289: generated MCP tool names are too long
### What version of Codex is running?

0.1.2505111730

### Which model were you using?

codex-mini-latest

### What platform is your computer?

unsure

### What steps can reproduce the bug?

This is based on this thread from the discussion forums:

https://github.com/openai/codex/discussions/1174#discussioncomment-13343602

Basically, the injected `__OAI_CODEX_MCP__` delimiter can cause things to tip over the 64-character limit

### What is the expected behavior?

Need to find a way to have multiple MCPs with a reliable disambiguation scheme that is less likely to trip the limit.

### What do you see instead?

```
ERROR: unexpected status 400 Bad Request: {  "error": {    "message": "Invalid 'tools[5].name': string too long. Expected a string with maximum length 64, but got a string with length 72 instead.",    "type": "invalid_request_error",    "param": "tools[5].name",    "code": "string_above_max_length"  }}
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by pakrym-oai**
Store fully qualified names along with tool entries so we don't have to re-parse them.

Fixes: https://github.com/openai/codex/issues/1289

### CODE REVIEW

**Comment by pakrym-oai** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bolinfest** [comment]
I haven't had a chance to review this properly yet, but FYI, you probably have to rebase on https://github.com/openai/codex/commit/0bc7ee91937d5cb9ff0e6a77e35cc89a91a81892

File: codex-rs/core/src/mcp_connection_manager.rs [hunk 1]
```diff
@@ -35,16 +40,41 @@ const LIST_TOOLS_TIMEOUT: Duration = Duration::from_secs(10);
 /// spawned successfully.
 pub type ClientStartErrors = HashMap<String, anyhow::Error>;
 
-fn fully_qualified_tool_name(server: &str, tool: &str) -> String {
-    format!("{server}{MCP_TOOL_NAME_DELIMITER}{tool}")
-}
+fn qualify_tools(tools: Vec<ToolInfo>) -> HashMap<String, ToolInfo> {
+    let mut used_names = HashSet::new();
```
Comment (bolinfest) [inline codex-rs/core/src/mcp_connection_manager.rs:45]: I think it could be slightly problematic to add a random suffix at the end of the string because if you are trying to do analysis across rollouts, the tool name will not be consistent. What do you think about the following strategy (now that we are keeping track of used names):

1. If `tool.tool_name` exceeds `MAX_TOOL_NAME_LENGTH`, go to Step 4.
2. If `tool.tool_name` is not in `used_names`, just use `tool.tool_name` as the qualified name.
3. If `{server_name}__{tool_name}` is not in `used_names` and does not exceed `MAX_TOOL_NAME_LENGTH`, use that as the qualified name.
4a. (Option 1) Take the hash (BLAKE3 or SHA256) of `{server_name}__{tool_name}` and use the 64-digit hex string as the qualified name.
4b. (Option 2) Take the first 24 characters of `tool_name` and concatenate it with the SHA1 of `{server_name}__{tool_name}`, which is a maximum of 64 digits.

Alternatively, we could just always hash, but I expect that makes things harder to debug.

I feel like Option 2 provides a good balance between consistency and readability. What do you think?

**Review by bolinfest — CHANGES_REQUESTED** [review]

File: codex-rs/core/src/mcp_connection_manager.rs (hunk 1 above)
Comment (pakrym-oai) [reply codex-rs/core/src/mcp_connection_manager.rs:45]: Agree with your comment. What I don't fully like in the approach is that tool names are order dependent. 

I'd rather always used `{server_name}__{tool_name}` and if it's too long appended SHA1 of `{server_name}__{tool_name}`.

How does this sound?

Comment (pakrym-oai) [reply codex-rs/core/src/mcp_connection_manager.rs:45]: Updated

File: codex-cli/bin/codex.js [hunk 2]
```diff
@@ -28,13 +28,14 @@ const __dirname = path.dirname(__filename);
 // For the @native release of the Node module, the `use-native` file is added,
 // indicating we should default to the native binary. For other releases,
 // setting CODEX_RUST=1 will opt-in to the native binary, if included.
-const wantsNative = fs.existsSync(path.join(__dirname, "use-native")) ||
+const wantsNative =
```
Comment (bolinfest) [inline codex-cli/bin/codex.js]: This is an unrelated change: would you mind removing this from the PR?

File: codex-rs/core/src/mcp_connection_manager.rs (hunk 1 above)
Comment (bolinfest) [reply codex-rs/core/src/mcp_connection_manager.rs:45]: That's a great point about the tool ordering: I like your solution!

File: codex-rs/core/src/mcp_connection_manager.rs [hunk 3]
```diff
@@ -224,3 +268,90 @@ fn is_valid_mcp_server_name(server_name: &str) -> bool {
...
+
+        assert_eq!(qualified_tools.len(), 2);
+
+        let mut keys: Vec<_> = qualified_tools.keys().cloned().collect();
+        keys.sort();
+
+        assert_eq!(keys[0].len(), 64);
+        assert_eq!(
+            keys[0],
+            "my_server__extremely_lena02e507efc5a9de88637e436690364fd4219e4ef"
```
Comment (bolinfest) [inline codex-rs/core/src/mcp_connection_manager.rs:348]: Seeing this an imagining trying to read it in logs or whatever, I wonder whether we would rather use 15 characters of prefix, `_` as a delimiter, and then the hash, so this would be:

```
my_server__extremely_le_a02e507efc5a9de88637e436690364fd4219e4ef
```

Though I guess that's not materially more readable? Just a thought: fine either way.

**Review by bolinfest — APPROVED** [review]
LGTM module the `codex.js` change!

File: codex-cli/bin/codex.js (hunk 2 above)
Comment (pakrym-oai) [reply codex-cli/bin/codex.js]: Done!

File: codex-rs/core/src/mcp_connection_manager.rs (hunk 3 above)
Comment (pakrym-oai) [reply codex-rs/core/src/mcp_connection_manager.rs:348]: I'd go with existing option and iterate if we feel the pain.
