### PR TITLE
Fix config documentation: correct TOML parsing description

### LINKED ISSUE #4531: Documentation inconsistency for `config` + MCP startup silently fails
### What version of Codex is running?

codex-cli 0.42.0

### Which model were you using?

gpt-5

### What platform is your computer?

Darwin 24.6.0 arm64 arm

### What steps can reproduce the bug?

Run `codex --help` and you will see that the documentation says that config overrides should be in JSON format. 

Image

If you look at [this](https://github.com/openai/codex/blob/main/docs/config.md#config) section of the README on Github on the other hand, it says you should use TOML format. 

I tried using JSON to configure and instantiate an MCP server at run time. Start up of the server failed silently, which is perhaps the more worrying bug. 

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by 0xRaduan**
The CLI help text and inline comments incorrectly stated that -c key=value flag parses values as JSON, when the implementation actually uses TOML parsing via parse_toml_value(). This caused confusion when users attempted to configure MCP servers using JSON syntax based on the documentation.

Changes:
- Updated help text to correctly state TOML parsing instead of JSON

Fixes #4531

### CODE REVIEW

**Comment by etraut-openai** [comment]
@codex review

File: codex-rs/common/src/config_override.rs [hunk 1]
```diff
@@ -59,12 +59,26 @@ impl CliConfigOverrides {
...
                 }
 
-                // Attempt to parse as JSON. If that fails, treat it as a raw
+                // Attempt to parse as TOML. If that fails, treat it as a raw
                 // string. This allows convenient usage such as
                 // `-c model=o3` without the quotes.
                 let value: Value = match parse_toml_value(value_str) {
                     Ok(v) => v,
-                    Err(_) => {
+                    Err(e) => {
```
Comment (etraut-openai) [inline codex-rs/common/src/config_override.rs]: I don't think the `eprintln` is the right way to report this error. This code path is used for multiple codex surfaces including the CLI and the extension. I can see an argument for providing better error handling in this code path, but doing so will require a much bigger change to properly propagate the error to callers. Please remove this part of the change.

**Review by etraut-openai — CHANGES_REQUESTED** [review]

File: codex-rs/common/src/config_override.rs (hunk 1 above)
Comment (0xRaduan) [reply codex-rs/common/src/config_override.rs]: Fair enough - thanks for the feedback!

**Comment by 0xRaduan** [comment]
@etraut-openai - addressed your comment

**Review by etraut-openai — APPROVED** [review]
