### PR TITLE
fix: add tui.alternate_screen config and --no-alt-screen CLI flag for Zellij scrollback

### LINKED ISSUE #2558: Codex client output truncated when scrolling in Zellij
### What version of Codex is running?

codex-cli 0.23.0

### Which model were you using?

gpt5

### What platform is your computer?

Darwin 24.6.0 arm64 arm

### What steps can reproduce the bug?

When running the Codex client inside a Zellij session, the output history does not display correctly. Attempting to scroll within the Zellij pane shows truncated content instead of the full history. This makes it difficult to review previously generated output.

Image

Image

Steps to reproduce it:

```
cargo install zellij
zellij
codex
```

Then try scrolling back using Zellij’s scroll mode.

### What is the expected behavior?

Scrolling in Zellij should display the full history of Codex output without truncation.

### What do you see instead?

Scrolling only shows partial output — earlier content is cut off.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by hjanuschka**
Fixes #2558

Codex uses alternate screen mode (CSI 1049) which, per xterm spec, doesn't support scrollback. Zellij follows this strictly, so users can't scroll back through output.

**Changes:**
- Add `tui.alternate_screen` config: `auto` (default), `always`, `never`
- Add `--no-alt-screen` CLI flag
- Auto-detect Zellij and skip alt screen (uses existing `ZELLIJ` env var detection)

**Usage:**
```bash
# CLI flag
codex --no-alt-screen

# Or in config.toml
[tui]
alternate_screen = "never"
```

With default `auto` mode, Zellij users get working scrollback without any config changes.

### CODE REVIEW

**Comment by hjanuschka** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hjanuschka** [comment]
recheck

**Comment by etraut-openai** [comment]
Thanks for the diagnosis and the PR.

I'm not that excited about exposing a configuration knob for this. We will probably look for a better solution. However, your diagnosis is valuable regardless.

I'll need to discuss with my colleagues to decide what to do here since I'm personally not that familiar with the TUI code. Most of the codex team is on holiday break, so it may be a week or more before we have a chance to discuss and make a decision.

**Comment by hjanuschka** [comment]
Hey, totally understand the hesitation on the config knob - I was not thrilled about it either tbh.

I spent some time digging into this to see if there is a better way. Here is what I found:

**On Zellij side:** They intentionally disabled scrollback in alternate screen (https://github.com/zellij-org/zellij/pull/1032) to follow the xterm spec strictly. This was not a bug - it is by design. The xterm spec says alternate screen buffers should not have scrollback, and Zellij follows that. There is no config option to change it and unlikely to ever be one.

**How others handle it:** tmux has `alternate-screen off` and terminal-overrides to disable smcup/rmcup. kitty has plugins for secondary screen access. But these are all variations of "don't use alternate screen" - there is no magic way to have both full-screen alt mode AND scrollback.

**Looking at TUI2:** I noticed the transcript-based architecture already prints history to scrollback on exit/suspend, which is great - but that does not help when you want to scroll back *during* the session without quitting. And while Ctrl+T opens the transcript pager, it is not the same as natural scrollback - you have to context-switch into a separate view.

So realistically the options are:
1. Detect Zellij and skip alternate screen (what this PR does)
2. Live with the Ctrl+T workaround (not ideal)

I am happy to strip out the config options entirely and just make it pure auto-detection if that feels cleaner? No user-facing knobs, just "it works in Zellij" silently.

No rush on this - enjoy the holidays! Just wanted to share what I found in case it is useful for the discussion.

**Comment by imsnif** [comment]
Hey, I hope you don't mind me chiming in. I came upon this PR because this issue has been reported quite a few times on the Zellij side.

@hjanuschka 's analysis is accurate. This is one of those "you can't have your cake and eat it" sort of situations. 

I don't know your requirements or time/workforce availability - but I think your utopian solution would be to implement scrollback on your own. If you control all the contents in the scrollback (and don't need to include output from arbitrary programs) this should be fairly straightforward. Otherwise, you can use some sort of off-the-shelf terminal emulation solution to do it for you.

Hope this helps.

**Comment by RickTorresJr** [comment]
Just want to provide additional context on how other LLM CLI tools handle this:
* Gemini CLI : 
  * Has config switch `ui.useAlternateBuffer` (default: `false`)
  * They default to no alternate buffer with opt-in for users who want it
* Claude Code:
    * Avoids the issue entirely by not using a TUI/alternate screen buffer
    *  Output goes to normal terminal stream so multiplexer scroll back works natively

**Comment by etraut-openai** [comment]
@hjanuschka, could you please resolve the merge conflicts and make sure the CI tests pass? Thanks!

**Comment by hjanuschka** [comment]
@etraut-openai  done, ~lets see if bots turn green~ all good

File: codex-rs/tui2/src/lib.rs [hunk 1]
```diff
@@ -515,12 +517,33 @@ async fn run_ratatui_app(
...
+                let terminal_info = codex_core::terminal::terminal_info();
+                !matches!(terminal_info.multiplexer, Some(Multiplexer::Zellij { .. }))
+            }
+        }
+    };
 
-    // Run the main chat + transcript UI on the terminal's alternate screen so
-    // the entire viewport can be used without polluting normal scrollback. This
-    // mirrors the behavior of the legacy TUI but keeps inline mode available
-    // for smaller prompts like onboarding and model migration.
```
Comment (joshka-oai) [inline codex-rs/tui2/src/lib.rs:523]: This comment still somewhat applies and should be kept

File: codex-rs/protocol/src/config_types.rs [hunk 2]
```diff
@@ -80,3 +80,23 @@ pub enum TrustLevel {
     Trusted,
     Untrusted,
 }
+
+/// Controls whether the TUI uses the terminal's alternate screen buffer.
+///
+/// Using alternate screen provides a cleaner fullscreen experience but prevents
+/// scrollback in terminal multiplexers like Zellij that follow the xterm spec
+/// (which says alternate screen should not have scrollback).
```
Comment (joshka-oai) [inline codex-rs/protocol/src/config_types.rs]: Expand on this with the context of the fix - there needs to be a good "in code" place where the rationale for why we're doing this is documented (so that devs / codex can have the "why?" answered in future).

I think this is probably the best place, but also feel free to add a small doc to the docs dir (you can copy the issue / PR context and get codex to generate it) This saves having to do issue archaeology later to answer why we do this.

File: codex-rs/tui/src/cli.rs [hunk 3]
```diff
@@ -85,6 +85,11 @@ pub struct Cli {
     #[arg(long = "add-dir", value_name = "DIR", value_hint = ValueHint::DirPath)]
     pub add_dir: Vec<PathBuf>,
 
+    /// Disable alternate screen mode for better scrollback in terminal multiplexers like Zellij.
+    /// This runs the TUI in inline mode, preserving terminal scrollback history.
```
Comment (joshka-oai) [inline codex-rs/tui/src/cli.rs]: Put a newline break here and split the description into what and why type message - clap shows the short description  with `-h`, long desc (both) with `--help`

Something like:
```rust
/// Disable alternate screen mode
///
/// ... reason / effect / etc.
```

File: codex-rs/tui/src/lib.rs [hunk 4]
```diff
@@ -493,7 +495,27 @@ async fn run_ratatui_app(
...
+    } else {
+        match config.tui_alternate_screen {
+            AltScreenMode::Always => true,
+            AltScreenMode::Never => false,
+            AltScreenMode::Auto => {
+                let terminal_info = codex_core::terminal::terminal_info();
+                !matches!(terminal_info.multiplexer, Some(Multiplexer::Zellij { .. }))
+            }
+        }
+    };
```
Comment (joshka-oai) [inline codex-rs/tui/src/lib.rs]: pull this into a small documented method - it's a good place to capture why we're doing this (maybe better / just as good as the other place.

**Review by joshka-oai — CHANGES_REQUESTED** [review]
LGTM generally - just doc nits that will help future devs / codex not have to dig through issues to work out the context of the changes here. The idea seems generally pragmatic as a workaround for the problem. 

Thanks for submitting.

Let me know how you go with the docs. I can also make the necessary changes to bring this up to a good polish on those too if you'd prefer.

Codex is good at adding this info - just tell it how to document the context, rationale, edge cases, complexity, etc. on all new items (structs, enums, methods etc.) and paste a copy of the the Issue / PR comments.

**Review by joshka-oai — APPROVED** [review]
LGTM - will run the pnpm format and push

**Comment by joshka-oai** [comment]
Thanks for the PR. I'll cut an alpha release with this in it later today - it would be great to hear back that it fixes your problems here. Incidentally we had another customer report this too, so thanks on their behalf!

**Comment by joshka-oai** [comment]
This should be in the v0.81.0-alpha.1 in about an hour.
