### PR TITLE
fix(tui): increase paste burst char interval on Windows to 30ms

### LINKED ISSUE #2137: Pasting multi-line text in Codex CIL only keeps first line and auto-submits on Windows
### What version of Codex is running?

v0.20.0

### Which model were you using?

_No response_

### What platform is your computer?

Windows

### What steps can reproduce the bug?

When pasting multi-line text into the Codex CIL chat input box, the input field does not handle line breaks properly.

Steps to Reproduce

Open the Codex CIL chat input box.

Copy a multi-line snippet (e.g., three lines of text).

Paste it into the input box.

Observed Behavior

Only the first line is shown in the input box.

The presence of a line break in the pasted content immediately triggers a “submit” action, sending the conversation automatically.

Impact
This prevents users from pasting multi-line commands, code blocks, or structured text,.

### What is the expected behavior?

All pasted lines should remain in the input box.

The user should be able to edit and review before sending.

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yuvrajangadsingh**
## Summary

- Increases `PASTE_BURST_CHAR_INTERVAL` from 8ms to 30ms on Windows to fix multi-line paste issues in VS Code integrated terminal
- Follows existing pattern of platform-specific timing (like `PASTE_BURST_ACTIVE_IDLE_TIMEOUT`)

## Problem

When pasting multi-line text in Codex CLI on Windows (especially VS Code integrated terminal), only the first portion is captured before auto-submit. The rest arrives as a separate message.

**Root cause**: VS Code's terminal emulation adds latency (~10-15ms per character) between key events. The 8ms `PASTE_BURST_CHAR_INTERVAL` threshold is too tight - characters arrive slower than expected, so burst detection fails and Enter submits instead of inserting a newline.

## Solution

Use Windows-specific timing (30ms) for `PASTE_BURST_CHAR_INTERVAL`, following the same pattern already used for `PASTE_BURST_ACTIVE_IDLE_TIMEOUT` (60ms on Windows vs 8ms on Unix).

30ms is still fast enough to distinguish paste from typing (humans type ~200ms between keystrokes).

## Test plan

- [x] All existing paste_burst tests pass
- [ ] Test multi-line paste in VS Code integrated PowerShell on Windows
- [ ] Test multi-line paste in standalone Windows PowerShell
- [ ] Verify no regression on macOS/Linux

Fixes #2137

### CODE REVIEW

**Comment by etraut-openai** [comment]
@codex review

**Comment by yuvrajangadsingh** [comment]
Addressed the review feedback:

**Fix**: Applied the same Windows-specific timing to `tui2/src/bottom_pane/paste_burst.rs` to keep both UIs aligned per the guidelines in `AGENTS.md`.

Now both `tui` and `tui2` have:
- `PASTE_BURST_CHAR_INTERVAL`: 8ms (Unix) / 30ms (Windows)

@codex review

**Comment by yuvrajangadsingh** [comment]
Rebased on latest main - tui2 paste_burst.rs was removed upstream, so changes now only apply to tui.

@codex review

**Comment by etraut-openai** [comment]
@yuvrajangadsingh, looks like there are some merge conflicts that need to be resolved.

**Comment by yuvrajangadsingh** [comment]
Rebased on latest main. Conflicts resolved.

@codex review

**Comment by yuvrajangadsingh** [comment]
@etraut-openai Conflicts resolved, rebased on latest main. CI passing, Codex review clean. Ready for review.

**Comment by yuvrajangadsingh** [comment]
Gentle ping - users are waiting for this fix. See https://github.com/openai/codex/issues/2137#issuecomment-3843422951

The PR is rebased and ready for review.

File: codex-rs/tui/src/bottom_pane/paste_burst.rs [hunk 1]
```diff
@@ -151,10 +151,18 @@ use std::time::Instant;
...
-// Slower paste burts have been observed in windows environments, but ideally
-// we want to keep this low
+
+// Maximum delay between consecutive chars to be considered part of a paste burst.
+// Windows terminals (especially VS Code integrated terminal) deliver paste events
+// more slowly than native terminals, so we use a higher threshold there.
+#[cfg(not(windows))]
+const PASTE_BURST_CHAR_INTERVAL: Duration = Duration::from_millis(8);
+#[cfg(windows)]
+const PASTE_BURST_CHAR_INTERVAL: Duration = Duration::from_millis(30);
```
Comment (joshka-oai) [inline codex-rs/tui/src/bottom_pane/paste_burst.rs:162]: Note that this is probably right on the threshold where we might from time to time detect actual typing as a paste for very fast typers typing common digraphs like 'th', 'er' etc. https://chatgpt.com/share/e/698b7f8e-4c10-8009-aa40-5e421aace79f

Not a blocker - just a note for if we do need to update this down a bit - 25ms would be a good target point (unless there's data to suggest that the pastes are taking this long on your system) If it becomes a bigger issue then we'd want this to be runtime configurable, but we can hold off on that for now.

**Review by joshka-oai — APPROVED** [review]
Thanks for the PR and apologies for the delay in getting it over the line and the churn getting there.

**Comment by joshka-oai** [comment]
Working out the bazel problems with this so we can merge it.

**Comment by etraut-openai** [comment]
@joshka-oai, we can ignore the bazel issues. Those actions will always fail for external contributions. I'll override and merge.
