### PR TITLE
fix(tui): rehydrate drafts and restore image placeholders

### LINKED ISSUE #9050: Ctrl+C stash drops large paste payloads when recalling history in TUI
## Summary
When a large paste is collapsed into a placeholder (e.g., "[Pasted Content ... chars]"), pressing Ctrl+C stashes the draft, but recalling it with Up-arrow loses the hidden payload. The placeholder remains as plain white text and submits literally, which effectively discards the original paste.

## Steps to Reproduce
1. Run Codex (either with TUI or `--enable tui2`)
2. Paste a large chunk of text so it collapses into a "[Pasted Content ... chars]" placeholder.
3. Press Ctrl+C to stash the draft.
4. Press Up-arrow to recall the draft from history.
5. Submit the message or inspect the placeholder styling.

## Expected
- The recalled draft preserves the hidden pasted content.
- The placeholder stays styled (blue) and expands to the original content on submit.

## Actual
- The placeholder becomes plain text (white) with no hidden payload.
- Submitting sends the literal placeholder text, losing the original paste.

### PR DESCRIPTION
**Pull request by Chriss4123**
Fixes #9050

When a draft is stashed with Ctrl+C, we now persist the full draft state (text elements, local image paths, and pending paste payloads) in local history. Up/Down recall rehydrates placeholder elements and attachments so styling remains correct and large pastes still expand on submit. Persistent (cross‑session) history remains text‑only.

Backtrack prefills now reuse the selected user message’s text elements and local image paths, so image placeholders/attachments rehydrate when rolling back.

External editor replacements keep only attachments whose placeholders remain and then normalize image placeholders to `[Image #1]..[Image #N]` to keep the attachment mapping consistent.

Docs:
- docs/tui-chat-composer.md

Testing:
- just fix -p codex-tui
- cargo test -p codex-tui

### CODE REVIEW

**Comment by Chriss4123** [comment]
@codex review

**Comment by etraut-openai** [comment]
Is there an open bug report related to this issue? Our contribution guidelines ask that all community bug fix PRs link to an associated bug report. This helps us track and prioritize issues, especially in cases where we decide to pass on a PR.

**Comment by Chriss4123** [comment]
> Is there an open bug report related to this issue? Our contribution guidelines ask that all community bug fix PRs link to an associated bug report. This helps us track and prioritize issues, especially in cases where we decide to pass on a PR.

@etraut-openai sorry, I forgot to do that. I've opened an issue [here](https://github.com/openai/codex/issues/9050).

File: codex-rs/tui/src/bottom_pane/chat_composer.rs [hunk 1]
```diff
@@ -377,6 +380,42 @@ impl ChatComposer {
         text
     }
 
+    fn pending_paste_occurrences(
```
Comment (joshka-oai) [inline codex-rs/tui/src/bottom_pane/chat_composer.rs]: Please add a doc comment to capture intent / algorithm notes. Perhaps some inline comments within this / small helper methods with intention revealing names would help. Right now I have to read every line of this method to understand its purpose, and how it solves that.

nit: I prefer to read code top to bottom, as the mental model of calling into code that's defined below is often neater when there are small methods that compose up. can you Move this below `set_text_content_with_pending`?

File: codex-rs/tui/src/bottom_pane/chat_composer.rs [hunk 2]
```diff
@@ -377,6 +380,42 @@ impl ChatComposer {
...
+        text: &str,
+        pending_pastes: &[(String, String)],
+    ) -> Vec<(usize, String)> {
+        let mut unique_placeholders = Vec::new();
+        let mut seen = HashSet::new();
+        for (placeholder, _) in pending_pastes {
+            if seen.insert(placeholder.as_str()) {
+                unique_placeholders.push(placeholder.as_str());
+            }
+        }
```
Comment (joshka-oai) [inline codex-rs/tui/src/bottom_pane/chat_composer.rs]: Prefer https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.unique if that would work here for clarity

File: codex-rs/tui/src/bottom_pane/chat_composer.rs [hunk 3]
```diff
@@ -377,6 +380,42 @@ impl ChatComposer {
...
+                occurrences.push((idx, placeholder.to_string()));
+                idx = idx.saturating_add(placeholder.len());
+            } else if let Some(ch) = slice.chars().next() {
+                idx = idx.saturating_add(ch.len_utf8());
+            } else {
+                break;
+            }
+        }
+        occurrences
+    }
```
Comment (joshka-oai) [inline codex-rs/tui/src/bottom_pane/chat_composer.rs]: I think this looks like https://crates.io/crates/aho-corasick/ probably, but it would probably be reasonable to store the positions of the placeholders directly when saving the ctrl+c so that restoring this is easy.

File: codex-rs/tui/src/bottom_pane/chat_composer.rs [hunk 4]
```diff
@@ -394,14 +433,68 @@ impl ChatComposer {
...
+        &mut self,
+        text: String,
+        pending_pastes: Vec<(String, String)>,
+    ) {
+        // Clear any existing content, placeholders, and attachments first.
+        self.textarea.set_text("");
+        self.pending_pastes.clear();
+        self.attached_images.clear();
+
+        if pending_pastes.is_empty() {
```
Comment (joshka-oai) [inline codex-rs/tui/src/bottom_pane/chat_composer.rs]: Describe each of the cases that end up here with a small // inline comment about what the scenario is. It's likely there should be a test case for each of these that aligns well with the comment.

File: codex-rs/tui/src/bottom_pane/chat_composer_history.rs [hunk 5]
```diff
@@ -4,6 +4,28 @@ use crate::app_event::AppEvent;
 use crate::app_event_sender::AppEventSender;
 use codex_core::protocol::Op;
 
+#[derive(Debug, Clone, PartialEq, Eq)]
+pub(crate) struct HistoryEntry {
```
Comment (joshka-oai) [inline codex-rs/tui/src/bottom_pane/chat_composer_history.rs]: Add doc comments here

**Review by joshka-oai — CHANGES_REQUESTED** [review]
I'm trying to generally ratchet up a bit on the comments that help explain how the various parts of this fit together as that's been generally neglected. This is secondary to the purpose here, but ask codex to add more information that would make this easy to review and maintain. Not a blocking part, just nice to have.

I think the main comment here is that this can be simplified by storing the placeholder locations when copying the history item out rather than by doing it on the other side (I think - not certain, please validate this and tell me I'm wrong).

Also, a few more tests for the different cases that are hit (again - I may be wrong on that)

File: codex-rs/tui/src/bottom_pane/chat_composer.rs (hunk 3 above)
Comment (Chriss4123) [reply codex-rs/tui/src/bottom_pane/chat_composer.rs]: I kept the string‑scan restore to match existing placeholder handling elsewhere in the composer to avoid widening the change: pending paste payloads are already rehydrated/expanded by scanning for the placeholder text. Storing placeholder positions requires expanding `HistoryEntry` and/or exposing element ranges from `TextArea`, which is quite invasive. I really wanted to do this from the beginning but my PR would have very likely been rejected had I done so - if you'd like me to do this I am more than happy; let me know.

**Comment by joshka-oai** [comment]
Testing with tui2, I see some extra characters that are added in the wrong place:

image

Note the ars and the s (the asdf is intentionally part of the prompt). Any ideas on this?

**Comment by charley-oai** [comment]
Btw [this PR](https://github.com/openai/codex/pull/9636) fixes this bug as well, but in a way that is compatible with [another fix](https://github.com/openai/codex/pull/9628)

**Comment by Chriss4123** [comment]
> Btw [this PR](https://github.com/openai/codex/pull/9636) fixes this bug as well, but in a way that is compatible with [another fix](https://github.com/openai/codex/pull/9628)

@charley-oai will take a look at this later today (been pretty busy) and let you know, but if it is better / more salient than my PR I am happy for you to move forward with that PR.

EDIT: done the changes - just need to review both impls but I think they are quite similar now really nice infra is set up (nice job on that Charley). Will update in a few hours.

**Comment by Chriss4123** [comment]
> Testing with tui2, I see some extra characters that are added in the wrong place:
> 
> image
> 
> Note the ars and the s (the asdf is intentionally part of the prompt). Any ideas on this?

@joshka-oai sorry for not addressing this timely - been really busy over the past few days.

It looks like you have gotten rid of tui2 completely; I am guessing I should remove that section from the PR. Will do that later today (and also handle any cascading changes from other commits) and review Charley's PR which could be a better fix as he said it is "compatible with another fix".

Will do all that in ~6-7 hours from now and let you know everything.

**Comment by Chriss4123** [comment]
@charley-oai @joshka-oai

I went back and handled all cascading changes with the new infra set up and broadened my PR to handle pastes and images instead of just pastes. I want to give a really special shoutout Charley because it really was pleasant to work with.

That being said, I re-read over both of our implementations quite a few times and I did notice a few suble potential issues regarding external editors and memory usage, although the memory usage is not that big of a deal as pastes are usually not excessively big.

I went and asked Codex w/ GPT-5.2-Codex-xhigh to do a read through too and it summed up all of my findings really nicely and succinctly so I'm just going to attach that and not re-litigate every nit/potential issue.

---

## Prompt

Deeply and extensively review `https://github.com/openai/codex/pull/9636` (you can use any `git` commands) and my implementation in the current branch (my branch has just a single commit for all changes within it).

Decide which implementation is stronger/better. Keep in mind tui2 has been fully retired from this repository.

You can run any command. I believe this PR may already be here locally - not sure. DO NOT use `web.run`.

---

## Response

**PR 9636 Findings**
- High: Updates retired tui2 code, which is now dead surface area and will conflict with removal; this makes the PR stale by default. `codex-rs/tui2/src/bottom_pane/chat_composer.rs:1`
- Medium: Ctrl+C history stashing clones full `pending_pastes`, duplicating potentially large payloads in memory; `mem::take` (or swap) avoids the extra copy. `codex-rs/tui/src/bottom_pane/chat_composer.rs:621`
- Low: The new external‑editor relabeling path has no targeted test in the PR, leaving a regression gap. `codex-rs/tui/src/bottom_pane/chat_composer.rs:478`

**Current Branch Findings**
- No correctness issues found in your changes.
- Residual risk: local history keeps full pending paste payloads in memory; repeated large pastes can grow session memory until exit.

**Decision**
- Your current‑branch implementation is stronger. It aligns with the repo state (no tui2), avoids extra large‑paste copies on Ctrl+C, adds broader tests (Ctrl+C draft rehydrate, image rehydrate, external‑edit renumbering), and documents the behavior more thoroughly. The PR’s only notable extra is the placeholder‑uniqueness doc comment in protocol, which is optional to port.

**Open Questions / Assumptions**
- I assumed tui2 is fully retired and should not be touched; confirm that’s still the intended direction.

**Optional Follow‑ups**
1. Port the placeholder‑uniqueness doc note from PR 9636 into `codex-rs/protocol/src/user_input.rs` if you want that detail centralized.  
2. If memory growth from large pending pastes is a concern, consider a size cap or eviction policy for `HistoryEntry::pending_pastes`.

---

So I'd probably lean to saying my PR is maybe a stronger candidate for optimally solving the issue I opened but of course there is no definitive answer and this is up for discussion. As you can see most of the issues Codex listed with your PR are pretty benign and easily fixeable so don't stress too much.

Anyways, interested to hear your guys' thoughts/opinions.

While I am fairly confident, you shouldn't take my or Codex's word for it as a source of truth. I recommend doing your own read throughs so we can all collaborate and benefit from one another.

Gonna go to bed now, will catch up with anything new tomorrow.

**Comment by Chriss4123** [comment]
@joshka-oai Fixed merge conflicts. Most of the conflict was because main already absorbed the newer composer/mention/footer refactors; I only reapplied the bits that were still unique here (draft history rehydrate + pending‑paste/image restore + docs/tests around that) so the PR has gotten considerably smaller but hasn't lost anything.

Also the one failing test looks like a flaky timeout. Can someone please re-run?

**Comment by joshka-oai** [comment]
>Also the one failing test looks like a flaky timeout. Can someone please re-run?

Will do.

(Sorry about the delay on this - it's on my backlog of things to get over the line this week)

**Comment by Chriss4123** [comment]
@codex review

**Comment by Chriss4123** [comment]
Latest push just fixed some merge issues that came up.

**Review by charley-oai — APPROVED** [review]
Thanks for bearing with us on this (we were super busy with the app launch and recent model release). PR looks good to me! I actually like it better than my PR now.
