### PR TITLE
fix: send non-null content on elicitation Accept

### LINKED ISSUE #9053: Elicitation fails with NoContent error when client sends empty content on Accept
### What version of Codex is running?

codex-cli 0.80.0

### What subscription do you have?

Enterprise

### Which model were you using?

gpt-5.2-codex medium

### What platform is your computer?

Darwin 25.3.0 arm64 arm

### What issue are you seeing?

When using MCP elicitation with clients like OpenAI Codex, the elicitation fails with NoContent error even when the user accepts the request.

The client (Codex) sends content: None in the CreateElicitationResult response when the user accepts:

```rust
ElicitationResponse {
    action: ElicitationAction::Accept,
    content: None,  // ← Bug: should contain the requested schema data
}
```
This is a known issue in Codex ([PR #6947 comment](https://github.com/openai/codex/pull/6947#discussion_r2550860067)):

"When the user accepts an elicitation request we still build the response with content: None, so the MCP server never receives the data it asked for via requested_schema."

### Expected Behavior:
When a tool requests elicitation with a schema like:

```rust
context.peer.elicit::<SubApproval>("Do you approve?").await
```
And the user accepts, the client should populate content with the schema data:

```json
{ "approved": true }
```
### Actual Behavior
Client sends content: None → server gets NoContent error → tool fails.

### What steps can reproduce the bug?

- Create tool with elicitation:
```rust
context.peer.elicit::<SubApproval>("Approve?").await
```
- Call tool from Codex
- Accept the elicitation prompt
- Observe: elicitation_failed: NoContent error

### What is the expected behavior?

When a tool requests elicitation with a schema like:

```rust
context.peer.elicit::<SubApproval>("Do you approve?").await
```
And the user accepts, the client should populate content with the schema data:

```json
{ "approved": true }
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yuvrajangadsingh**
## Summary

- When a user accepts an MCP elicitation request, send `content: Some(json!({}))` instead of `None`
- MCP servers that use elicitation expect content to be present when action is Accept
- This matches the expected behavior shown in tests at `exec-server/tests/common/lib.rs:171`

## Root Cause

In `codex-rs/core/src/codex.rs`, the `resolve_elicitation` function always sent `content: None`:

```rust
let response = ElicitationResponse {
    action,
    content: None,  // Always None, even for Accept
};
```

## Fix

Send an empty object when accepting:

```rust
let content = match action {
    ElicitationAction::Accept => Some(serde_json::json!({})),
    ElicitationAction::Decline | ElicitationAction::Cancel => None,
};
```

## Test plan

- [x] Code compiles with `cargo check -p codex-core`
- [x] Formatted with `just fmt`
- [ ] Integration test `accept_elicitation_for_prompt_rule` (requires MCP server binary)

Fixes #9053

### CODE REVIEW

**Comment by etraut-openai** [comment]
@codex review

File: codex-rs/core/src/codex.rs [hunk 1]
```diff
@@ -2064,10 +2064,13 @@ mod handlers {
             codex_protocol::approvals::ElicitationAction::Decline => ElicitationAction::Decline,
             codex_protocol::approvals::ElicitationAction::Cancel => ElicitationAction::Cancel,
         };
-        let response = ElicitationResponse {
-            action,
-            content: None,
+        // When accepting, send an empty object as content to satisfy MCP servers
+        // that expect non-null content on Accept. For Decline/Cancel, content is None.
+        let content = match action {
+            ElicitationAction::Accept => Some(serde_json::json!({})),
```
Comment (bolinfest) [inline codex-rs/core/src/codex.rs:2070]: Seems reasonable.

FYI, I did some related work on the MCP Inspector: https://github.com/modelcontextprotocol/inspector/pull/926.

**Review by bolinfest — APPROVED** [review]
