### PR TITLE
fix: filter dynamic deferred tools from model_visible_specs

### LINKED ISSUE #19486: [P0 / Blocker] Remote compact task fails 100% with "tools.defer_loading requires tools.tool_search" — GPT-5.5 unusable at context limit, no client-side workaround
## Severity: Blocker / P0

Codex becomes unusable the moment any non-trivial conversation reaches the auto-compact threshold. **100% reproducible.** **No viable client-side workaround** — rolling back the desktop app does not help because the failing call is constructed server-side.

This bug effectively makes the headline GPT-5.5 launch experience on Codex desktop dead on arrival for anyone running the default plugin set.

## Environment

- Codex desktop (macOS, Apple Silicon)
  - Reproduced on **26.422.30944** (current)
  - Reproduced on **26.422.21459** after manual rollback — identical failure
- Model: **GPT-5.5**, reasoning effort \`xhigh\`
- Plugins enabled (default-ish set): \`github\`, \`browser-use\`, \`documents\`, \`spreadsheets\`, \`presentations\`, \`computer-use\`

## Error

As soon as the conversation hits the compact threshold:

\`\`\`
Error running remote compact task: {
  "error": {
    "message": "Invalid Value: 'tools.defer_loading'. Deferred tools require tools.tool_search.",
    "type": "invalid_request_error",
    "param": "tools.defer_loading",
    "code": null
  }
}
\`\`\`

The session stalls. Every retry reproduces the same 400. The conversation cannot progress.

## Reproduction

1. Install Codex desktop 26.422.x on Apple Silicon.
2. Select GPT-5.5.
3. Keep default plugins enabled so tool descriptions cross the ~10% context threshold that auto-enables \`tool_search\` + \`defer_loading\`.
4. Work normally until the conversation approaches the compact threshold.
5. The remote compact endpoint returns the 400 above — every time, with no recovery path.

## Likely root cause

The server-side compact task (\`chatgpt.com/backend-api/codex/responses/compact\`) rebuilds the Responses API payload with \`defer_loading\` on individual tool entries but **omits the paired \`tool_search\` entry** at the top level of the \`tools\` array. The Responses API then rejects its own internally-constructed request. This regression coincides with \"tool discovery enabled by default\" in the recent changelog.

In other words: the server is failing its own schema validation against itself.

## Why the obvious workarounds do not work

- **Rolling back the desktop client (30944 → 21459):** identical failure. Compact is remote — client version is irrelevant.
- **Starting new threads:** resets context, but any substantive session hits the same wall again.
- **Switching to GPT-5.4:** \`defer_loading\` was introduced in 5.4, so it almost certainly exercises the same path.
- **Disabling plugins** until tool descriptions drop under the ~10% threshold is the only thing that *might* avoid it — i.e., asking paying users to disable advertised features to get the product to function.

## Impact

- GPT-5.5 + Codex desktop is **non-functional for any user with the default plugin set** as soon as a conversation fills.
- This is the flagship model from last week's launch.
- There is no preserved-functionality workaround.
- The fix does not require a client release — it is a pure server-side correction in the compact-task request builder.

## Requested fix

Either:
- (a) Include \`tool_search\` in the rebuilt compact request whenever any tool entry carries \`defer_loading\`, **or**
- (b) Strip \`defer_loading\` from tool entries in the rebuilt compact request when \`tool_search\` is intentionally omitted.

Please prioritize. This is a top-of-funnel regression on a paid flagship model.

## Related

- #19009 — Compact fails in CLI and VS Code Extension
- #19279 — Experimental feature check disabling app startup
- #19295 — White screen on v26.422.21637 (Pro)
- #19370 — GPT-5.5 not usable in Codex App for remote projects

### PR DESCRIPTION
**Pull request by sayan-oai**
fixes #19486

### Problem
Right now dynamic deferred tools are filtered at normal-turn prompt building time, rather than upstream while building the `ToolRouter` itself. This causes issues because dynamic deferred tools are then wrongly included in the router's `model_visible_specs`, which is what the compaction request-building flow relies on.

### Fix
Move the dynamic deferred tool filtering to `ToolRouter` creation time to solve this problem for every request that relies on `ToolRouter` for `model_visible_specs`, which solves the issue generically.

### Tests
Added unit + integration tests to ensure dynamic deferred tools are omitted from `model_visible_specs` and compaction request respectively.

Tested against live `/compact` endpoint; raw deferred dynamic tools without `tool_search` returned `400` (current bug), while the filtered payload (this fix) returns `200`.

### CODE REVIEW

File: codex-rs/core/src/tools/router.rs [hunk 1]
```diff
@@ -71,23 +71,26 @@ impl ToolRouter {
...
-                    }
-                })
-                .collect()
-        } else {
-            specs
-                .iter()
-                .map(|configured_tool| configured_tool.spec.clone())
-                .collect()
-        };
+        let deferred_dynamic_tools = dynamic_tools
```
Comment (pakrym-oai) [inline codex-rs/core/src/tools/router.rs:74]: instead of post filtering can we not add deferred tools to specs?

Comment (sayan-oai) [reply codex-rs/core/src/tools/router.rs:74]: code mode builds its `ALL_TOOLS` list from `router.specs()`, and the specs are used to create code mode tool definitions (name, schema, description, etc.). so the tools have to be present in `specs()`, but not `model_visible_specs()`.

for MCPs, code mode registers all MCP tools as direct while building its nested router so that `specs()` is fully populated and can be used to build `ALL_TOOLS` as described.

**Review by pakrym-oai — APPROVED** [review]
--
