### PR TITLE
fix: resume lookup for gitignored CODEX_HOME

### LINKED ISSUE #5412: Cannot resume sessions when setting variable
### What version of Codex is running?

codex-cli 0.47.0

### What subscription do you have?

PRO

### Which model were you using?

Codex high

### What platform is your computer?

24.5.0 arm64 arm

### What issue are you seeing?

When I launch commands like: 

CODEX_HOME=/Users/myusername/Documents/Personal/Whatour/config/runtime/codex/fsdfds codex exec --json --skip-git-repo-check resume 019a03bf-3490-7733-bfb6-0376f023c045 "did i tell you my name? "

It does not restore the context, it creates a new session every single time. It happens only when I specify the CODEX_HOME path, if not, it works.

### What steps can reproduce the bug?

Launch codex resume for sessions while specifying CODEX_HOME to a different directory. It will not work and will create a new sesson,  ignoring the resume.

### What is the expected behavior?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tibo-openai**
Walk the sessions tree instead of using file_search so gitignored CODEX_HOME directories can resume sessions. Add a regression test that covers a .gitignore'd sessions directory.

Fixes #5247
Fixes #5412

### CODE REVIEW

File: codex-rs/core/src/rollout/list.rs [hunk 1]
```diff
@@ -492,35 +490,79 @@ pub async fn find_conversation_path_by_id_str(
...
-        compute_indices,
-    )
-    .map_err(|e| io::Error::other(format!("file search failed: {e}")))?;
-
-    Ok(results
-        .matches
-        .into_iter()
-        .next()
-        .map(|m| root.join(m.path)))
+    let codex_home = codex_home.to_path_buf();
```
Comment (pakrym-oai) [inline codex-rs/core/src/rollout/list.rs]: Should we use something like walkdir instead of rolling our own dir walking logic?

File: codex-rs/core/src/rollout/list.rs [hunk 2]
```diff
@@ -492,35 +490,79 @@ pub async fn find_conversation_path_by_id_str(
...
+    let id = id_str.to_owned();
+
+    spawn_blocking(move || {
```
Comment (pakrym-oai) [inline codex-rs/core/src/rollout/list.rs]: why spawn?

**Review by pakrym-oai — COMMENTED** [review]
I'm getting a bit uncomfortable with how many file walker implementations we have.

**Comment by MarianoFacundoArch** [comment]
Necessary fix, though!

**Review by pakrym-oai — APPROVED** [review]
