### PR TITLE
fix(tui): show in-flight coalesced tool calls in transcript overlay

### LINKED ISSUE #7998: Bug: Transcript view omits in-progress “Explored” tool calls until a later flush
## Summary
When using the interactive Codex TUI, pressing `Ctrl+T` to open the transcript overlay while the agent is actively running “exploring” tool calls (reads/searches/lists that are coalesced into a single `• Exploring` / `• Explored` block) shows the agent’s reasoning/status, but not the underlying tool calls and their outputs. The missing tool calls appear later (retroactively) after some unrelated boundary event occurs (e.g., the agent prints normal text or runs a non-“exploring” command).

Users expecting real-time visibility will find coalescable commands absent until a flush boundary, creating a misleading gap between what's shown and what's actually running.

Image
Image

https://github.com/user-attachments/assets/0b786fcb-4ddd-4739-a891-ec9b515dd315

## Steps to reproduce
1. Run `codex` inside a repository.
2. Give the agent a task that causes multiple filesystem exploration commands (e.g., `ls`, `find`, `rg`, `cat`, etc.).
3. While the agent is still issuing those exploration commands (and the main UI shows a single coalesced `• Exploring` section), press `Ctrl+T`.
4. Observe that the transcript overlay does not include the `Exploring/Explored` tool-call block.
5. Wait until the agent prints any normal assistant text (or runs a non-“exploring” command), then open the transcript again (or keep it open).
6. Observe that the previously missing tool calls now appear, making the transcript feel “retroactively fixed”.

## Expected behavior
The transcript overlay should reflect everything the UI currently knows about the ongoing turn, including the currently-active coalesced tool-call block.

## Actual behavior
The transcript overlay renders only committed history cells, so the currently-active coalesced tool-call block is missing until it gets flushed.

## Root cause
This TUI intentionally coalesces “exploring” tool calls into a single in-flight history cell (`ChatWidget.active_cell`, typically an `ExecCell`) so the main view can show one grouped block like:

- `• Exploring` / `• Explored`
  - `Read …`, `Search …`, `List …` (etc.)

That *in-flight* cell is rendered in the main viewport immediately, but it is not committed into `App::transcript_cells` (via `InsertHistoryCell`) until a later boundary triggers `flush_active_cell()` (e.g., the agent starts streaming normal text, or a non-coalescable command forces a new exec cell).

The transcript overlay (opened via `Ctrl+T`) is constructed solely from `App::transcript_cells`, so it cannot see `ChatWidget.active_cell`. As a result, while the agent is only executing coalesced “exploring” commands, the transcript overlay can show other committed transcript content (e.g., reasoning/status) but not the tool activity that’s still buffered in the active exec group. When a later boundary flushes the active cell, the whole coalesced block gets inserted, and the transcript appears to “catch up” retroactively.

A contributing factor is “transcript-only” reasoning cells: these can be committed to the transcript without flushing the active exec group, increasing the mismatch (transcript shows “thoughts”, but the “Explored” block is still uncommitted).

## Notes
- Reproduces in both `codex-tui` and `codex-tui2`.

### PR DESCRIPTION
**Pull request by Chriss4123**
Fixes #7998.

The TUI coalesces read/search/list exec calls into an in-flight "Exploring/Explored" group (ChatWidget.active_cell). The main viewport renders that active cell immediately, but the Ctrl+T transcript overlay was built only from committed transcript cells, so while the agent is still exploring the overlay can look like the tool calls are missing until a later flush boundary.

This PR makes the transcript overlay include a render-only "live tail" for the current active history cell. It doesn’t change when exec groups flush or how coalescing works; it just makes the overlay reflect what the UI already knows.

To keep overlay interactions cheap, the tail is cached and only recomputed when the active cell changes or the terminal width changes.

Testing:
- cargo test -p codex-tui
- cargo test -p codex-tui2

### CODE REVIEW

File: codex-rs/tui/src/app_backtrack.rs [hunk 1]
```diff
@@ -218,6 +218,33 @@ impl App {
...
+            {
+                tui.frame_requester()
+                    .schedule_frame_in(std::time::Duration::from_millis(50));
+            }
+            if close_overlay {
+                self.close_transcript_overlay(tui);
+                tui.frame_requester().schedule_frame();
+            }
+            return Ok(());
+        }
```
Comment (joshka-oai) [inline codex-rs/tui/src/app_backtrack.rs:271]: (ask codex to) Summarize what this new code does better here - someone has to read every line to understand how this works / what the expectation of this code is. Capture the context and help make it easier to understand the context of why this code does what it does.

File: codex-rs/tui/src/chatwidget.rs [hunk 2]
```diff
@@ -370,6 +371,13 @@ pub(crate) struct ChatWidget {
     external_editor_state: ExternalEditorState,
 }
 
+#[derive(Clone, Copy, Debug, PartialEq, Eq)]
+pub(crate) struct ActiveCellTranscriptKey {
+    pub(crate) revision: u64,
+    pub(crate) is_stream_continuation: bool,
+    pub(crate) animation_tick: Option<u64>,
+}
```
Comment (joshka-oai) [inline codex-rs/tui/src/chatwidget.rs:426]: Add doc comments to help answer 'why does this struct exist' (context / link it back to how it solves this problem).
At the field level - tell me what these track, how they help the solution etc. Why is a revision necessary?

Mindset should be as a developer reading this code for the first time, what do I need to know to orient myself easily against the rest of the code base.

(codex is pretty good at adding this info but generally has to be asked to)

File: codex-rs/tui/src/chatwidget.rs [hunk 3]
```diff
@@ -2215,6 +2231,10 @@ impl ChatWidget {
         self.frame_requester.schedule_frame();
     }
 
+    fn bump_active_cell_revision(&mut self) {
+        self.active_cell_revision = self.active_cell_revision.wrapping_add(1);
```
Comment (joshka-oai) [inline codex-rs/tui/src/chatwidget.rs:2326]: What happens when this wraps. Does all matter in the universe convert to paperclips? ;)
https://en.wikipedia.org/wiki/Universal_Paperclips

File: codex-rs/tui/src/pager_overlay.rs [hunk 4]
```diff
@@ -404,9 +405,18 @@ pub(crate) struct TranscriptOverlay {
...
     is_done: bool,
 }
 
+#[derive(Clone, Copy, Debug, PartialEq, Eq)]
+struct LiveTailKey {
+    width: u16,
+    revision: u64,
+    is_stream_continuation: bool,
+    animation_tick: Option<u64>,
+}
```
Comment (joshka-oai) [inline codex-rs/tui/src/pager_overlay.rs:448]: As above - comments

File: codex-rs/tui/src/pager_overlay.rs [hunk 5]
```diff
@@ -459,21 +470,101 @@ impl TranscriptOverlay {
...
+                    as Box<dyn Renderable>
+            } else {
+                tail
+            };
+            self.view.renderables.push(tail);
+        }
+        if follow_bottom {
+            self.view.scroll_offset = usize::MAX;
+        }
+    }
```
Comment (joshka-oai) [inline codex-rs/tui/src/pager_overlay.rs:539]: More docs on how this works needed here - let codex summarize this a bunch

File: codex-rs/tui/src/pager_overlay.rs [hunk 6]
```diff
@@ -459,21 +470,101 @@ impl TranscriptOverlay {
...
+
+    pub(crate) fn sync_live_tail(
+        &mut self,
```
Comment (joshka-oai) [inline codex-rs/tui/src/pager_overlay.rs:554]: and docs here

**Review by joshka-oai — CHANGES_REQUESTED** [review]
Thanks - the idea looks good and it definitely solves the problem.

My comments generally are around adding extra context around the changes to the code. This helps people (and agents) unfamiliar with the specific code paths be able to validate the code actually aligns with what it's intended to do.

I'd merge this with that extra info. Happy to update this for you, or let you go at it if you'd prefer. Mostly codex does a really good job here at adding this info with extra prompts to add the right level of docs (whereeve context / rationale / edge cases / complexity / large abstraction level gaps is needed). Mostly doc comments, some inline.

**Comment by joshka-oai** [comment]
@codex review this to ensure that the tui/tui2 behavior and code is the same (modulo any changes that tui2 would prevent this).

File: codex-rs/tui/src/pager_overlay.rs [hunk 7]
```diff
@@ -459,21 +470,101 @@ impl TranscriptOverlay {
...
+    ) {
+        let next_key = active_key.map(|key| LiveTailKey {
+            width,
+            revision: key.revision,
+            is_stream_continuation: key.is_stream_continuation,
+            animation_tick: key.animation_tick,
+        });
+
+        if self.live_tail_key == next_key {
+            return;
```
[the remark this answers is not in the document]
Comment (Chriss4123) [reply codex-rs/tui/src/pager_overlay.rs:567]: Helpful catch. The changes that made the overlay stale were introduced a few days after my live-tail work and I didn't re-review my code for correctness with that new behavior.

Fixed by bumping the revision when the wait cell updates or is replaced, with tests.

**Comment by Chriss4123** [comment]
> Thanks - the idea looks good and it definitely solves the problem.
> 
> My comments generally are around adding extra context around the changes to the code. This helps people (and agents) unfamiliar with the specific code paths be able to validate the code actually aligns with what it's intended to do.
> 
> I'd merge this with that extra info. Happy to update this for you, or let you go at it if you'd prefer. Mostly codex does a really good job here at adding this info with extra prompts to add the right level of docs (whereeve context / rationale / edge cases / complexity / large abstraction level gaps is needed). Mostly doc comments, some inline.

Applied all of your suggestions. Please take another look when you get the time.

**Comment by Chriss4123** [comment]
@codex review

File: codex-rs/tui/src/chatwidget.rs (hunk 3 above)
Comment (Chriss4123) [reply codex-rs/tui/src/chatwidget.rs:2326]: Haha, I think it would take a few hundred billion years under normal circumstances for this to wraparound.

File: codex-rs/tui/src/history_cell.rs [hunk 8]
```diff
@@ -100,6 +100,12 @@ pub(crate) trait HistoryCell: std::fmt::Debug + Send + Sync + Any {
     fn is_stream_continuation(&self) -> bool {
         false
     }
+
+    /// If set, the transcript output is time-dependent and should be re-rendered when the tick
+    /// changes (e.g. for animated spinners/shimmers).
+    fn transcript_animation_tick(&self) -> Option<u64> {
+        None
```
[the remark this answers is not in the document]
Comment (Chriss4123) [reply codex-rs/tui/src/history_cell.rs]: Fixed. `UnifiedExecWaitCell` now emits transcript animation ticks so the shimmer stays live in the overlay.

**Comment by Chriss4123** [comment]
@codex review

**Comment by Chriss4123** [comment]
@joshka-oai I think it's ready for a re-review.

**Comment by Chriss4123** [comment]
The failing test looks like a flaky timeout. Other platforms passed and this PR only touches `tui`/`tui2`.

Can someone rerun the Windows ARM job?

**Comment by joshka-oai** [comment]
I added a bunch of docs in ba041f8d201456e7e7fd204b7c5d76ad7969a675 to help understand how this works a bit better.

Codex prompt for the docs update: (generated by GPT 5.2 and then tweaked a bit after looking at the output).

<details><summary>Prompt</summary>
<p>

````
You are in **DOCUMENTATION PASS** mode.

This is a *non-functional* pass over an existing change.
Your job is to make the system understandable to humans without altering what it does.

---

## **Hard rules**

You MUST:

* Not change runtime behavior
* Not refactor logic
* Not rename public APIs unless required for clarity (if so, propose instead of doing)
* Not delete code

You MAY:

* Add or edit documentation comments
* Add module headers
* Improve commit messages
* Improve PR description text
* Add or adjust tests only if they clarify intent (prefer none)

If you believe a code change is needed for clarity, **call it out but do not implement it.**

---

## **Documentation style rules (Rust-aware)**

When writing Rust documentation:

* The first paragraph of every doc comment must be a single-sentence summary.
* Follow with normal narrative paragraphs, not labeled sections.
* Do NOT invent headings like “Overview”, “Postcondition”, or “Misuse”.
* Integrate guarantees, assumptions, and pitfalls into prose.
* Use `# Errors`, `# Panics`, or `# Safety` only when they are genuinely required by Rustdoc conventions.
* Misuse examples should appear as natural warnings in text, not as standalone sections.

Inline comments inside functions must follow this rule:

* Comments that explain **design, ownership, layering, invariants, or architecture** belong in **doc comments**.
* Inline comments should only explain **local logic** (why this branch, why this calculation).
* If a comment would still be true if the function body were rewritten, it must be a doc comment.

For module-level docs:

* Describe **invariants and mechanisms**, not “things going wrong”.
* Prefer “The overlay is kept in sync by…” over “If the overlay looks stale…”.

---

## **Your goals**

Convert implicit intent into explicit narrative.

A reviewer should be able to answer:

* *What problem does this solve?*
* *How does this subsystem work?*
* *What are the contracts and invariants?*
* *What could break and how would I debug it?*

---

## **Step 1 — PR-level narrative**

Write (or rewrite) a PR description that includes:

**Problem**

* What user or system pain this change addresses

**Mental model**

* How this part of the system works after the change

**Non-goals**

* What was intentionally NOT done

**Tradeoffs**

* What was sacrificed or risked

**Architecture**

* How this interacts with existing subsystems

**Observability**

* How to tell this is working or broken

**Tests**

* What was added/changed and why it is sufficient

Avoid line-by-line diff walkthroughs.

---

## **Step 2 — Intent vs implementation**

Infer the intended design from the code.

Then list:

* Where the implementation clearly matches that intent
* Where it is ambiguous, leaky, or inconsistent
* What minimal documentation would remove that ambiguity

Be blunt.

---

## **Step 3 — Module-level documentation**

For every non-trivial module, write or update a header doc comment that explains:

* What problem this module solves
* The key concepts and terms used here
* Responsibilities vs non-responsibilities
* How it fits into the larger system
* Any state machine or lifecycle it manages
* Where invariants are enforced and by which components

Use narrative prose, not API listings.

---

## **Step 4 — Type-level documentation**

For every public struct, enum, trait, or type, document:

* Its role in the system
* What it represents conceptually
* The invariants it maintains
* Who is allowed to construct or mutate it
* Threading or ownership assumptions

Do NOT restate field names — explain meaning and contracts.

---

## **Step 5 — Function-level documentation**

For every public function or method, document:

* Why it exists
* When it should be used
* Preconditions and assumptions
* Postconditions and guarantees
* What errors mean and how callers should respond
* One realistic misuse case and what bug it would cause

Do not translate the signature into English.

---

## **Step 6 — Implicit contracts**

List the real contracts this change introduces:

* Which are enforced by types
* Which are enforced by tests
* Which are only assumptions in developers’ heads

Recommend where each should be documented.

---

## **Step 7 — Debuggability**

Describe:

* Which components are responsible for keeping key invariants true
* Where state is synchronized or cached
* What logs, flags, or entry points matter when tracing behavior

This should read as architecture, not as a list of bugs.

---

## **Step 8 — Commit story**

Rewrite or propose commit messages so that each commit answers:

* What changed in system behavior
* Why it changed
* What it enables or blocks next

Avoid “refactor”, “cleanup”, or “minor”.

---

## **Final output**

Produce:

1. Updated PR description
2. Documentation patches (module, type, function)
3. A short list of **design inconsistencies or risks** you discovered

If something doesn’t make sense, say so.

You are not here to be polite — you are here to make the system legible.
````

</p>
</details> 

And output:

## Updated PR description

### Problem
Ctrl+T transcript overlay can omit in-flight coalesced tool calls because it
renders only committed transcript cells while the main viewport can render the
current in-flight ChatWidget.active_cell immediately.

### Mental model
The UI has both committed transcript cells (finalized HistoryCell entries) and
an in-flight active cell that can mutate in place while streaming, often
representing a coalesced exec/tool group. The transcript overlay renders
committed cells plus a render-only live tail derived from the current active
cell. The live tail is cached and only recomputed when its cache key changes,
which is derived from terminal width (wrapping), active-cell revision
(in-place mutations), stream continuation (spacing), and animation tick
(time-based visuals).

### Non-goals
This does not change coalescing rules, flush boundaries, or when active cells
become committed. It does not change tool-call semantics or transcript
persistence; it is a rendering-only improvement for the overlay.

### Tradeoffs
This adds cache invalidation complexity: correctness depends on bumping an
active-cell revision (and/or providing an animation tick) when the active cell
mutates in place. The mechanism is implemented in both codex-tui and codex-tui2,
which keeps behavior consistent but risks drift if future changes are not
applied in lockstep.

### Architecture
App special-cases transcript overlay draws to sync a live tail from ChatWidget
into TranscriptOverlay. TranscriptOverlay remains the owner of committed
transcript cells; the live tail is an optional appended renderable.
HistoryCell::transcript_animation_tick() allows time-dependent transcript output
(spinner/shimmer) to invalidate the cached tail without requiring data mutation.

### Observability
Manual verification is to open Ctrl+T while an exploring/coalesced active cell
is still in-flight and confirm the overlay includes the same in-flight tool-call
group the main viewport shows. The overlay is kept in sync by App passing an
active-cell key and transcript lines into TranscriptOverlay::sync_live_tail; the
key must change when the active cell mutates or animates.

### Tests
Snapshot tests validate that the transcript overlay renders a live tail appended
after committed cells and that identical keys short-circuit recomputation. Unit
tests validate that active-cell revision bumps occur on specific in-place
mutations (e.g. unified exec wait cell command display becoming known late) so
cached tails are invalidated.

## Documentation patches (module, type, function)

### Module-level docs (invariants + mechanisms)
- codex-rs/tui/src/app_backtrack.rs:1
- codex-rs/tui/src/chatwidget.rs:1
- codex-rs/tui/src/pager_overlay.rs:1
- codex-rs/tui/src/history_cell.rs:1
- codex-rs/tui2/src/app_backtrack.rs:1
- codex-rs/tui2/src/chatwidget.rs:1
- codex-rs/tui2/src/pager_overlay.rs:1
- codex-rs/tui2/src/history_cell.rs:1

### Type-level docs (cache key + invariants)
- codex-rs/tui/src/chatwidget.rs (ChatWidget.active_cell_revision, ActiveCellTranscriptKey)
- codex-rs/tui/src/pager_overlay.rs (TranscriptOverlay live tail storage model)
- codex-rs/tui/src/history_cell.rs (HistoryCell::transcript_animation_tick, UnifiedExecWaitCell::update_command_display)
- Mirrored in codex-rs/tui2/src/chatwidget.rs, codex-rs/tui2/src/pager_overlay.rs, codex-rs/tui2/src/history_cell.rs

### Function-level docs (why/when/guarantees/pitfalls)
- codex-rs/tui/src/app_backtrack.rs (overlay_forward_event)
- codex-rs/tui/src/chatwidget.rs (active_cell_transcript_key, active_cell_transcript_lines)
- codex-rs/tui/src/pager_overlay.rs (sync_live_tail, take_live_tail_renderable)
- codex-rs/tui/src/history_cell.rs (transcript_animation_tick, UnifiedExecWaitCell::update_command_display)
- Mirrored in codex-rs/tui2 equivalents where present

### Validation performed
- cd codex-rs && just fmt
- cd codex-rs && cargo test -p codex-tui
- cd codex-rs && cargo test -p codex-tui2

## Design inconsistencies / risks

- Cache invalidation is a distributed responsibility: any future in-place active
  cell transcript mutation that forgets to bump active_cell_revision (or expose
  an animation tick) can leave the transcript overlay live tail out of sync with
  the main viewport.
- TranscriptOverlay tail handling assumes a structural invariant that the live
  tail, when present, is exactly one trailing renderable after the committed cell
  renderables; if renderable construction changes in a way that violates that
  assumption, tail insertion/removal logic becomes incorrect.
- codex-tui and codex-tui2 duplicate the live-tail mechanism; the documentation
  is aligned, but the implementation can still drift unless changes continue to
  be applied in lockstep.

**Review by joshka-oai — APPROVED** [review]
