### PR TITLE
fix: Update seatbelt policy for java on macOS

### LINKED ISSUE #3978: Cannot run java/jdk commands in macOS sandbox
### What version of Codex is running?

codex-cli 0.39.0

### Which model were you using?

gpt-5-codex high

### What platform is your computer?

Darwin 25.0.0 arm64 arm

### What steps can reproduce the bug?

To do java development I need to have the sandbox be able to run java/jdk related commands. The java command is /usr/bin/java and is using /usr/libexec/java_home. It does a kind a discovery mechanism to run the jdk located in my case in /Library/Java/JavaVirtualMachines/amazon-corretto-24.jdk/Contents/Home.

Somehow some directories are not readable in the sandbox which makes running fail:

❯ codex debug seatbelt /usr/bin/java
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

The target directory where the jdk is installed is readable in the sandbox so by doing:

export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-24.jdk/Contents/Home

I can run the jdk. I gave this information as an instruction to codex and it could run mvn, java, etc. This is a workaround for now.

### What is the expected behavior?

Be able to run java and jdk commands from the sandbox.

### What do you see instead?

❯ codex debug seatbelt /usr/bin/java
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bn3t**
# Summary

This PR is related to the Issue #3978 and contains a fix to the seatbelt profile for macOS that allows to run java/jdk tooling from the sandbox. I have found that the included change is the minimum change to make it run on my machine.

There is a unit test added by codex when making this fix. I wonder if it is useful since you need java installed on the target machine for it to be relevant. I can remove it it is better.

Fixes #3978

### CODE REVIEW

**Comment by bn3t** [comment]
I have read the CLA Document and I hereby sign the CLA

File: codex-rs/core/tests/suite/seatbelt.rs [hunk 1]
```diff
@@ -197,6 +197,69 @@ async fn python_getpwuid_works_under_seatbelt() {
...
+
+    let policy = SandboxPolicy::ReadOnly;
+    let command_cwd = std::env::current_dir().expect("getcwd");
+    let sandbox_cwd = command_cwd.clone();
+
+    let mut env: HashMap<String, String> = std::env::vars().collect();
+    env.remove("JAVA_HOME");
+    env.remove(CODEX_SANDBOX_ENV_VAR);
+
+    let mut child = spawn_command_under_seatbelt(
```
Comment (nornagon-openai) [inline codex-rs/core/tests/suite/seatbelt.rs]: I think `cargo clippy` is asking you to drop the `mut` here
```suggestion
    let child = spawn_command_under_seatbelt(
```

**Comment by nornagon-openai** [comment]
Overall looks good, just a minor lint issue.

**Comment by bn3t** [comment]
I pushed a fix for the test. Please confirm you want to keep the test, btw.

**Comment by charlieforward9** [comment]
Looking for this to make it in soon! Nearly all of my codex responses contain: 

```
  └ The operation couldn’t be completed. Unable to locate a Java Runtime.
    Please visit http://www.java.com for information on installing Java.
```

**Review by aibrahim-oai — APPROVED** [review]
Approving after syncing with @nornagon-openai

**Comment by etraut-openai** [comment]
@bn3t, thanks for the contribution. I think this will make a lot of Codex users happy!
