### PR TITLE
Always enable plan tool in exec

### LINKED ISSUE #5359: bug: codex exec Fails to Call Plan Tool Due to Misconfigured Default
### What version of Codex is running?

codex-cli 0.47.0

### What subscription do you have?

pro

### Which model were you using?

gpt-5-codex

### What platform is your computer?

_No response_

#### Description

When running the `codex exec` command, there is an issue where the plan tool is not invoked as expected. The process continuously tries to invoke `update_plan` but fails due to the plan tool being disabled. This behavior occurs because of a default configuration that forces the plan tool to be turned off, even when it's required by the agent.

#### Log Output

```plaintext
thinking
**Preparing to update plan**
tool codex.list_mcp_resource_templates({"cursor":null})
codex.list_mcp_resource_templates({"cursor":null}) success in 0ms:
{
  "content": [
    {
      "text": "{\"resourceTemplates\":[]}",
      "type": "text"
    }
  ],
  "isError": false
}
thinking
**Verifying access to update_plan tool**
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo 'plan'" in /home/usaco/CSES/1069 succeeded in 6ms:
plan
thinking
**Preparing plan update call**
exec
/bin/bash -lc 'cd /home/usaco/CSES/1069 && pwd' in /home/usaco/CSES/1069 succeeded in 6ms:
/home/usaco/CSES/1069
thinking
**Calling update plan function**
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo '??'" in /home/usaco/CSES/1069 succeeded in 5ms:
??
thinking
**Preparing to call update_plan**
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo 'update plan? nope'" in /home/usaco/CSES/1069 succeeded in 6ms:
update plan? nope
thinking
**Noticing plan update needed**
exec
/bin/bash -lc 'cd /home/usaco/CSES/1069 && ls' in /home/usaco/CSES/1069 succeeded in 7ms:
AGENTS.md
main.cpp
README.md
sample.in
sample.out
thinking
**Correcting approach with update_plan**
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo 'Stop messing, use plan tool'" in /home/usaco/CSES/1069 succeeded in 6ms:
Stop messing, use plan tool
Re-connecting... 1/100
thinking
**Planning to call update_plan**
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo 'no plan tool??'" in /home/usaco/CSES/1069 succeeded in 5ms:
no plan tool??
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo 'impossible? wait'" in /home/usaco/CSES/1069 succeeded in 5ms:
impossible? wait
thinking
**Considering direct message for update**
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo '(:'" in /home/usaco/CSES/1069 succeeded in 5ms:
(:
thinking
**Preparing to update plan**
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo 'can't call update_plan??'" in /home/usaco/CSES/1069 exited 2 in 5ms:
/bin/bash: -c: line 1: unexpected EOF while looking for matching `''
thinking
**Correcting update_plan call**
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo 'wtf'" in /home/usaco/CSES/1069 succeeded in 6ms:
wtf
thinking
**Preparing to update plan**
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo 'Focus'"! Need update_plan call via tool interface. Can'"'t use shell.'" in /home/usaco/CSES/1069 exited 2 in 5ms:
/bin/bash: -c: line 1: unexpected EOF while looking for matching `''
thinking
**Reviewing tool communication method**
exec
/bin/bash -lc 'cd /home/usaco/CSES/1069 && echo "Focus time"' in /home/usaco/CSES/1069 succeeded in 5ms:
Focus time
thinking
**Pausing the process**
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo 'calling plan tool soon'" in /home/usaco/CSES/1069 succeeded in 4ms:
calling plan tool soon
thinking
**Preparing to send update to plan function**
exec
/bin/bash -lc "cd /home/usaco/CSES/1069 && echo 'this is going nowhere'" in /home/usaco/CSES/1069 succeeded in 5ms:
this is going nowhere
```

#### Root Cause

1. **Configuration Override**: In `codex-rs/exec/src/lib.rs`, the construction of `ConfigOverrides` always forces `include_plan_tool: Some(false)` unless explicitly overridden by `--include-plan-tool`. This effectively disables the plan tool by default.

2. **Default Value Issue**: In `codex-rs/exec/src/cli.rs`, the default value for `--include-plan-tool` is `false`, which means that even if the user doesn’t make any changes, the plan tool is disabled through the above override logic.

3. **Contradiction with Command Instructions**: The latest agent documentation still requires the use of the plan tool (`plan tool`). As a result, when `codex exec` disables the plan tool due to the configuration override, the agent’s attempt to call `update_plan` is rejected.

#### Why the "Messy Output" Happens

* **Fallback After Plan Call Failure**: After failing to call the plan tool, the agent continues to try to call `update_plan`. However, because the plan tool is disabled, Codex falls back to using the default shell commands to output messages like "no plan tool." This results in repeated shell command outputs that are seen as "messy."

* **Comparison with TUI**: The TUI version has `include_plan_tool: Some(true)` set explicitly in `codex-rs/tui/src/lib.rs`, which prevents this issue, making Codex’s behavior more opaque when failures occur.

#### Suggested Solution

To restore normal behavior, consider adjusting the default value in the CLI configuration or removing the hardcoded `Some(false)` override in the configuration logic. This will allow the tool to follow either the global default or the user's specified configuration, enabling the plan tool when necessary.

### What steps can reproduce the bug?

codex exec --skip-git-repo-check "design an apple website"

### What is the expected behavior?

```
codex exec --skip-git-repo-check "design an apple website"
OpenAI Codex v0.47.0 (research preview)
--------
workdir: /home/usaco/CSES_jingao/tmp
model: gpt-5-codex
provider: crs
approval: never
sandbox: danger-full-access
reasoning effort: high
reasoning summaries: auto
session id: 0199ff42-091e-7a21-a3fe-550cf424c464
--------
user
design an apple website

thinking
**Preparing to inspect workspace**
exec
ls in /home/usaco/CSES_jingao/tmp succeeded in 3ms:


thinking
**Drafting project plan for Apple-style website**
2025-10-20T01:35:58.740350Z ERROR codex_core::exec: exec error: No such file or directory (os error 2)
exec
update_plan '[{"step":"Define site structure","status":"in_progress"},{"step":"Build key sections","status":"pending"},{"step":"Apply Apple-style styling","status":"pending"},{"step":"Polish responsiveness","status":"pending"}]' in /home/usaco/CSES_jingao/tmp exited -1 in 0ms:
No such file or directory (os error 2)
```

### Additional information
_No response_

### PR DESCRIPTION
**Pull request by pakrym-oai**
Fixes: https://github.com/openai/codex/issues/5359

### CODE REVIEW

File: codex-rs/exec/src/lib.rs [hunk 1]
```diff
@@ -177,7 +181,7 @@ pub async fn run_main(cli: Cli, codex_linux_sandbox_exe: Option<PathBuf>) -> any
         model_provider,
         codex_linux_sandbox_exe,
         base_instructions: None,
-        include_plan_tool: Some(include_plan_tool),
+        include_plan_tool: Some(include_plan_tool.unwrap_or(true)),
```
Comment (jif-oai) [inline codex-rs/exec/src/lib.rs:184]: Keep it as optional and set it here instead
https://github.com/openai/codex/blob/0e8d937a3f3b8fb756f8ce0b6492f30fa9a4a6e7/codex-rs/core/src/features.rs#L232

**Review by jif-oai — CHANGES_REQUESTED** [review]

**Review by jif-oai — APPROVED** [review]
