### PR TITLE
fix: update file search directory when session CWD changes

### LINKED ISSUE #9041: @filename lookup broken: “no matches” in trusted roots
### What version of Codex is running?

  0.80.0

  ### What subscription do you have?

  Plus

  ### Which model were you using?

  Codex (GPT-5) — issue not model-specific

  ### What platform is your computer?

  Darwin 24.6.0 arm64

  ### What issue are you seeing?

  Summary
  After starting Codex in a non‑git folder and choosing “Require approval of edits and commands,” @filename
  stops working in trusted workspaces and returns “no matches.” This side effect is non‑obvious and appears
  unrelated to safety.

  ### What steps can reproduce the bug?

  1. Start Codex in a non‑git folder.
  2. Choose “Require approval of edits and commands.”
  3. Open a trusted workspace and use @filename.

  ### What is the expected behavior?

  @filename resolves consistently in trusted workspaces.

  ### Additional information

  I tried removing the persisted trust entry in the TOML config; it sometimes helps after a terminal restart but
  not reliably. This suggests the issue isn’t fully resolved by deleting that entry alone.

### PR DESCRIPTION
**Pull request by yuvrajangadsingh**
## Summary

Fixes #9041

- Adds update_search_dir() method to FileSearchManager to allow updating the search directory after initialization
- Calls this method when the session CWD changes: new session, resume, or fork

## Problem

The FileSearchManager was created once with the initial search_dir and never updated. When a user:

1. Starts Codex in a non-git directory (e.g., /tmp/random)
2. Resumes or forks a session from a different workspace
3. The @filename lookup still searched the original directory

This caused no matches to be returned even when files existed in the current workspace.

## Solution

Update FileSearchManager.search_dir whenever the session working directory changes:
- AppEvent::NewSession: Use current config CWD
- SessionSelection::Resume: Use resumed session CWD
- SessionSelection::Fork: Use forked session CWD

## Test plan

- [ ] Start Codex in /tmp/test-dir (non-git)
- [ ] Resume a session from a project with actual files
- [ ] Verify @filename returns matches from the resumed session directory

### CODE REVIEW

**Comment by etraut-openai** [comment]
@codex review

**Comment by etraut-openai** [comment]
@yuvrajangadsingh, thanks for the contribution. Please take a look at the code review comment from Codex.

**Comment by yuvrajangadsingh** [comment]
Thanks for the review! I've addressed the feedback:

- `update_search_dir` now cancels any in-flight search via the cancellation token
- Clears `active_search`, `latest_query`, and `is_search_scheduled` to prevent stale results

This ensures old searches from the previous workspace can't pollute the new session.

**Comment by yuvrajangadsingh** [comment]
@codex review

**Comment by yuvrajangadsingh** [comment]
Addressed the second review comment as well:

**Fix**: Moved `search_dir` into `SearchState` (inside the mutex) so the debounce thread reads the **current** value when it fires, not a stale captured value.

Before: `search_dir` was captured at thread spawn time → race condition
After: `search_dir` read from mutex after debounce → always current

@codex review

**Comment by yuvrajangadsingh** [comment]
Addressed the third round of feedback:

**Fix**: Skip search if `latest_query` is empty when debounce fires.

This handles the case where `update_search_dir()` cleared the state while the debounce thread was sleeping - prevents expensive match-all traversal.

@codex review

File: codex-rs/tui/src/app.rs [hunk 1]
```diff
@@ -675,6 +675,8 @@ impl App {
                 };
                 self.chat_widget = ChatWidget::new(init, self.server.clone());
                 self.current_model = model_info.slug.clone();
+                // Update file search directory to match the current config's cwd.
```
Comment (etraut-openai) [inline codex-rs/tui/src/app.rs]: These changes need to be mirrored into the tui2 parallel directory. We're currently exploring a different tui implementation, so for the time being, we need to keep the two in sync.

**Review by etraut-openai — CHANGES_REQUESTED** [review]

**Comment by yuvrajangadsingh** [comment]
Mirrored the changes to tui2 as requested. Both tui and tui2 now have:

- `update_search_dir` method in `file_search.rs`
- `search_dir` stored inside `SearchState` (mutex-protected) to prevent race conditions
- Empty query check to avoid expensive match-all traversal
- `update_search_dir` calls in NewSession, Resume, and ForkCurrentSession handlers in `app.rs`

All tests pass for both packages.

**Comment by yuvrajangadsingh** [comment]
@etraut-openai Changes mirrored to tui2 as requested. Ready for another look!

@codex review

**Comment by yuvrajangadsingh** [comment]
Addressed the P3 feedback: added a generation counter to invalidate stale debounce threads after session changes.

**How it works:**
- `generation` field added to `SearchState`
- Incremented in `update_search_dir()` on session change
- Debounce threads capture generation at spawn time
- Before proceeding with search, check if generation matches - if not, abort silently

This prevents duplicate searches when user types a new query before the old debounce fires.

@etraut-openai @codex review

File: codex-rs/tui/src/file_search.rs [hunk 2]
```diff
@@ -72,12 +75,30 @@ impl FileSearchManager {
...
+        let mut st = self.state.lock().unwrap();
+        st.search_dir = new_dir;
+        if let Some(active_search) = &st.active_search {
+            active_search
+                .cancellation_token
+                .store(true, Ordering::Relaxed);
+        }
+        st.active_search = None;
+        st.latest_query.clear();
+        st.is_search_scheduled = false;
```
[the remark this answers is not in the document]
Comment (yuvrajangadsingh) [reply codex-rs/tui/src/file_search.rs]: Addressed: Added a `generation` counter to `SearchState`. It's incremented in `update_search_dir()` and debounce threads check if generation matches before proceeding - if not, they abort silently.

File: codex-rs/tui2/src/file_search.rs [hunk 3]
```diff
@@ -72,12 +75,30 @@ impl FileSearchManager {
...
+        let mut st = self.state.lock().unwrap();
+        st.search_dir = new_dir;
+        if let Some(active_search) = &st.active_search {
+            active_search
+                .cancellation_token
+                .store(true, Ordering::Relaxed);
+        }
+        st.active_search = None;
+        st.latest_query.clear();
+        st.is_search_scheduled = false;
```
[the remark this answers is not in the document]
Comment (yuvrajangadsingh) [reply codex-rs/tui2/src/file_search.rs]: Addressed: Same fix applied to tui2 - added `generation` counter with the same behavior.

File: codex-rs/tui/src/app.rs (hunk 1 above)
Comment (yuvrajangadsingh) [reply codex-rs/tui/src/app.rs]: Done! All changes mirrored to tui2:
- `file_search.rs`: `update_search_dir`, `search_dir` in mutex, empty query check, generation counter
- `app.rs`: `update_search_dir` calls in NewSession, Resume, and ForkCurrentSession handlers

**Comment by yuvrajangadsingh** [comment]
Rebased on latest main to resolve conflicts.

@codex review

**Comment by yuvrajangadsingh** [comment]
@etraut-openai All changes addressed - generation counter added to prevent duplicate debounce searches, mirrored to tui2. Conflicts resolved, CI passing, Codex review clean. Ready for final review.

**Comment by yuvrajangadsingh** [comment]
Rebased again on latest main to resolve new conflicts.

@codex review

**Comment by yuvrajangadsingh** [comment]
Rebased on latest main - tui2 was removed upstream, changes now only apply to tui.

@codex review

**Comment by yuvrajangadsingh** [comment]
@codex review

**Review by etraut-openai — APPROVED** [review]

File: codex-rs/tui/src/file_search.rs [hunk 4]
```diff
@@ -42,6 +42,17 @@ impl FileSearchManager {
         }
     }
 
+    /// Updates the directory used for file searches.
+    /// This should be called when the session's CWD changes (e.g., on new session, resume, or fork).
```
Comment (etraut-openai) [inline codex-rs/tui/src/file_search.rs]: This comment looks wrong. I think this should be called only on resume. For new sessions, the FileSearchManager is created with the correct cwd from the start. For forks, the cwd doesn't change.

**Review by etraut-openai — CHANGES_REQUESTED** [review]
Looking pretty good. One small change request.

File: codex-rs/tui/src/file_search.rs (hunk 4 above)
Comment (yuvrajangadsingh) [reply codex-rs/tui/src/file_search.rs]: Fixed. Updated the docstring to only mention resume.

**Comment by yuvrajangadsingh** [comment]
@etraut-openai Fixed the docstring - now only mentions resume. Ready for another look.

**Review by etraut-openai — APPROVED** [review]
