### PR TITLE
fix: wrap long exec lines in transcript overlay

### LINKED ISSUE #7454: Ctrl+T transcript overlay truncates very long single lines instead of wrapping to viewport width
### What version of Codex is running?

codex-cli 0.63.0

### What subscription do you have?

API

### Which model were you using?

gpt-5.1-codex

### What platform is your computer?

Linux 6.6.87.2-microsoft-standard-WSL2 x86_64 x86_64 (Windows 11 host with WSL2 Ubuntu)

### What issue are you seeing?

 In the Ctrl+T transcript overlay, very long single lines are rendered as a single on‑screen row and simply cut off at the right edge of the terminal, instead of being wrapped to the viewport width.

  This makes it impossible to inspect the full content of very long tool outputs or command outputs in the transcript view: you only see the leftmost part of the line, and there is no horizontal scrolling or soft-wrapping applied there.

  In my case, I reproduced this with a Python tool call that prints a single line of about 1,000 characters. In the normal TUI view, the output is visible, but when I open the Ctrl+T transcript overlay the same output appears as only one row and is truncated to the terminal width.

### What steps can reproduce the bug?

  1. Start `codex` in a terminal.

  2. In the composer, send a message that makes Codex run a tool/exec command which prints a single extremely long line (around 1,000 characters). For example, ask it something like:

     `Execute a tool call, using Python to print a very long single line (1000 characters). I need to test if this project correctly displays long text.`

     Concretely, Codex ends up running something like:
     - `python -c "print('X'*1000, end='')"`

  3. Wait for the tool call / command to finish.

  4. Optionally scroll the normal TUI view and confirm that the output is present (it may be wrapped or partially visible there, but it is at least accessible).

Image

  5. Press `Ctrl+T` to open the transcript overlay.

  6. In the transcript overlay, locate the tool/exec output from step 2.
     - You will see that the 1,000-character line is rendered as a single row and is cut off at the viewport width.
     - There is no soft wrapping within the transcript overlay and no horizontal scroll, so the majority of the line cannot be viewed.

Image

### What is the expected behavior?

  I expect the Ctrl+T transcript overlay to be width-aware and to soft-wrap long logical lines to the current viewport width, just like other TUI components that render history lines.

  Concretely:

  - A very long single line (e.g. 1,000 characters of Python output) should wrap into multiple on‑screen rows in the transcript overlay so that the full content is readable with normal vertical scrolling.
  - The effective height of the transcript for that entry should reflect the wrapped height, so that paging/scrolling behaves consistently.
  - Alternatively, if hard wrapping is not desired, there should be some way to inspect the full line (e.g. horizontal scrolling or a dedicated view), but the current behavior of silently truncating at the right edge gives no way to see the full output.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by muyuanjin**
What
-----
- Fix the Ctrl+T transcript overlay so that very long exec output lines are soft‑wrapped to the viewport width instead of being rendered as a single truncated row.
- Add a regression test to `TranscriptOverlay` to ensure long exec outputs are rendered on multiple lines in the overlay.

Why
----
- Previously, the transcript overlay rendered extremely long single exec lines as one on‑screen row and simply cut them off at the right edge, with no horizontal scrolling.
- This made it impossible to inspect the full content of long tool/exec outputs in the transcript view, even though the main TUI view already wrapped those lines.
- Fixes #7454.

How
----
- Update `ExecCell::transcript_lines` to wrap exec output lines using the existing `RtOptions`/`word_wrap_line` helpers so that transcript rendering is width‑aware.
- Reuse the existing line utilities to expand the wrapped `Line` values into the transcript overlay, preserving styling while respecting the current viewport width.
- Add `transcript_overlay_wraps_long_exec_output_lines` test in `pager_overlay.rs` that constructs a long single‑line exec output, renders the transcript overlay into a small buffer, and asserts that the long marker string spans multiple rendered lines.

### CODE REVIEW

**Comment by etraut-openai** [comment]
Thanks for the contribution. Before I assign it to someone on the codex team for review, please fix the CI failure. Looks like a simple formatting issue (cargo fmt).

**Comment by muyuanjin** [comment]
> Thanks for the contribution. Before I assign it to someone on the codex team for review, please fix the CI failure. Looks like a simple formatting issue (cargo fmt).

Thanks for pointing that out. I’ve updated the formatting in the PR, and the CI is now passing.

File: codex-rs/tui/src/pager_overlay.rs [hunk 1]
```diff
@@ -748,6 +748,49 @@ mod tests {
         assert_snapshot!("transcript_overlay_apply_patch_scroll_vt100", snapshot);
     }
 
+    #[test]
+    fn transcript_overlay_wraps_long_exec_output_lines() {
```
Comment (joshka-oai) [inline codex-rs/tui/src/pager_overlay.rs:752]: This test seems a bit more complex than I'd like to see in a test, but it's sort of in pattern for the existing code. I wonder if it could be simplified to be more hard coded (e.g. check a snapshot). The perspective is that I have to really read every line of the test carefully to understand what property of the code this is testing.

Some small things that reduce line count are intermediate vars (e.g. 
```
let command_output = CommandOutput {...};
exec_cell.complete_call("exec-long", command_output, Duration::from_millis(10));
```

But also perhaps a snapshot instead of counting lines etc.

I'm very much of the opinion that generally tests should generally be simpler than the behavior they're testing. Here that seems inverted.

**Review by joshka-oai — APPROVED** [review]
Impl LGTM. nit about the test. I think it could be improved for maintainability. Not a blocker however. I'd suggest throw codex at the test and see if it does better.

File: codex-rs/tui/src/pager_overlay.rs (hunk 1 above)
Comment (etraut-openai) [reply codex-rs/tui/src/pager_overlay.rs:752]: Yeah, I'm not convinced a test is really needed in this case.

I'm going to merge and then address the test as a follow-up PR.
