### PR TITLE
tui: stabilize shortcut overlay snapshots on WSL

### LINKED ISSUE #9361: WSL: shortcut overlay snapshot tests are non-deterministic
### What version of Codex is running?

Built from source (codex-rs TUI).

### What platform is your computer?

WSL2 (Windows).

### What issue are you seeing?

Snapshot tests for the TUI shortcut overlay are non-deterministic under WSL.

On WSL, Codex detects the environment and renders the paste-image shortcut as `Ctrl+Alt+V` (many terminals intercept `Ctrl+V`), while non-WSL renders `Ctrl+V`.

Because the snapshot output depends on this detection, running `cargo test -p codex-tui` / `cargo test -p codex-tui2` under WSL can fail with diffs like:
- `ctrl + v to paste images` → `ctrl + ⌥ + v to paste images`

### What steps can reproduce the bug?

1. Run Codex from source under WSL2.
2. Run the TUI unit tests:
   - `cargo test -p codex-tui`
   - `cargo test -p codex-tui2`
3. Observe snapshot failures in footer/shortcut overlay tests.

### What is the expected behavior?

Snapshot tests should be deterministic across environments. WSL-specific runtime behavior is fine, but unit test snapshots should not depend on host detection.

### Additional information

A fix is proposed in PR #9359: gate WSL detection behind `cfg(not(test))` (runtime unchanged) and add a focused unit test that still asserts the WSL-specific paste-image binding.

### PR DESCRIPTION
**Pull request by slkzgm**
Fixes #9361

## Context
Split out from #9059 per review: https://github.com/openai/codex/pull/9059#issuecomment-3757859033

## Summary
The shortcut overlay renders different paste-image bindings on WSL (Ctrl+Alt+V) vs non-WSL (Ctrl+V), which makes snapshot tests non-deterministic when run under WSL.

## Changes
- Gate WSL detection behind `cfg(not(test))` so snapshot tests are deterministic across environments.
- Add a focused unit test that still asserts the WSL-specific paste-image binding.

## Testing
- `just fmt`
- `just fix -p codex-tui`
- `just fix -p codex-tui2`
- `cargo test -p codex-tui`
- `cargo test -p codex-tui2`

### CODE REVIEW

**Comment by etraut-openai** [comment]
@codex review

File: codex-rs/tui/src/bottom_pane/footer.rs [hunk 1]
```diff
@@ -8,7 +8,7 @@
 //! Some footer content is time-based rather than event-based, such as the "press again to quit"
 //! hint. The owning widgets schedule redraws so time-based hints can expire even if the UI is
 //! otherwise idle.
-#[cfg(target_os = "linux")]
+#[cfg(all(target_os = "linux", not(test)))]
```
Comment (joshka-oai) [inline codex-rs/tui/src/bottom_pane/footer.rs]: I don't like having test related cfg checks in non-test code like this. It makes it difficult to reason about how the behavior works as different behavior under tests is usually not something that most people will anticipate. Likely this instead should be separate test behavior that triggers based on the test environment.

This probably means that we need to investing in actually setting up our CI to have a WSL specific test in the matrix.

**Comment by joshka-oai** [comment]
I resolved the `jj git fetch` bookmark conflict by selecting the correct branch tip and cleaning up the remaining `footer.rs` conflict; I also dropped the obsolete `tui2` footer file (since `tui2` has been deleted).

I made the WSL-specific shortcut overlay behavior deterministic for snapshots, while keeping a unit test that still asserts the WSL paste-image binding (Ctrl+Alt+V vs Ctrl+V).

I also ran clippy (`just fix -p codex-tui`) and fixed the macOS lint issue around WSL detection.

Updated commit: c5c847db6de9

I’ve pushed the updated branch to your fork (`slkzgm`).

**Review by joshka-oai — APPROVED** [review]
