### PR TITLE
fix: diff_buffers clear-to-end when deleting wide graphemes

### LINKED ISSUE #4870: Windows: Korean IME preedit shows blanks or disappears only in Codex CLI
### What version of Codex is running?

v0.44.0

### Which model were you using?

gpt-5 medium 

### What platform is your computer?

Microsoft Windows NT 10.0.26100.0 x64

### What steps can reproduce the bug?

 - Summary                                                                                    
      - On Windows, when typing Korean with the system IME inside Codex CLI, characters under  
        composition (preedit) intermittently render as blanks or disappear; deletions can also 
        leave apparent gaps. This only happens in Codex; other terminals/apps behave normally. 
  - Expected                                                                                   
      - Preedit text renders in place without blanks; cursor width/position stays consistent;  
        backspace does not leave gaps.                                                         
  - Actual                                                                                     
      - During composition, some Hangul jamo/syllables momentarily render as empty cells or    
        vanish. On delete, spacing/cursor appears off, visually leaving blanks.                
  - Scope                                                                                      
      - Reproducible only in Codex CLI; same machine/IME/fonts do not show the issue elsewhere.  - Environment                                                                                
      - OS: Windows 10/11 (user report)                                                        
      - Shell: PowerShell/Windows Terminal/VS Code Terminal (issue persists across terminals)  
      - IME: Microsoft Korean IME                                                              
      - Fonts: Tried multiple monospace fonts; no resolution                                   
      - Codex CLI: current public release (exact version unknown)                              
  - Attempts/Workarounds                                                                       
      - Tried different terminals and fonts; turned off colors/emoji; updated terminal; no     
        effective workaround—issue remains specific to Codex CLI.                              
  - Hypothesis
      - TUI input/render loop interferes with IME preedit on Windows: alternate screen/full re-        render during composition, inconsistent wcwidth for CJK, or lack of explicit preedit   
        handling.                                                                              
  - Suggestions                                                                                
      - Add a “plain input” mode that minimizes re-render during IME composition.              
      - Defer full-screen redraws while receiving composition events; ensure width calc uses   
        consistent wcwidth and treats variation selectors/emoji off.                           
      - Verify Windows IME inline composition handling in the TUI layer (e.g., crossterm/rx/   
        ratatui equivalents) and guard cursor updates during composition.                      
  - Impact                                                                                     
      - High for Korean users: frequent input errors and poor UX during normal typing.         
                                                                                               
  이슈 본문 (Korean)                                                                           
                                                                                               
  - 요약                                                                                       
      - Windows에서 Codex CLI 내 한글 입력 시, 조합(미리편집) 중 일부 글자가 공란처럼 보이거나 
        사라지고, 삭제 시 빈칸이 남는 것처럼 보입니다. 동일 환경의 다른 앱/터미널에서는 재현되 
        지 않으며, Codex에서만 발생합니다.                                                     
  - 기대 동작                                                                                  
      - 조합 중 글자가 정상 표시되고 커서/폭이 어긋나지 않음.                                  
  - 실제 동작                                                                                  
      - 조합 중 특정 자모/음절이 공백처럼 보이거나 깜빡 사라짐. 백스페이스 시 시각적으로 공백이        남는 것처럼 보임.
  - 범위                                                                                       
      - Codex CLI에서만 재현(사용자 보고); 폰트/터미널 변경으로도 해소되지 않음.               
  - 환경                                                                                       
      - Windows 10/11, PowerShell/Windows Terminal/VS Code 터미널                              
      - 마이크로소프트 한글 IME                                                                
      - 여러 모노스페이스 폰트 시도(무효)                                                      
      - Codex CLI 버전: 최신(정확 버전 미기재)                                                 
  - 시도한 우회                                                                                
      - 색상/이모지 비활성, 폰트/터미널 교체, 업데이트 등—효과 없음. Codex에서만 동일 증상.    
  - 원인 가설                                                                                  
      - IME 미리편집과 TUI 리렌더/커서 업데이트 충돌, CJK 폭 계산 불일치, Windows IME 인라인 조        합 미처리.                                                                             
  - 개선 제안                                                                                  
      - IME 조합 중 전체 리렌더 최소화하는 “plain/simple input 모드” 추가.                     
      - 조합 이벤트 수신 동안 커서/리렌더 제어, 폭 계산 일관화.                                
      - Windows IME 인라인 조합 경로를 명시적으로 처리.                                        
  - 영향                                                                                       
      - 한국어 사용자 입력 경험에 큰 영향.   

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MomentDerek**
fix #4870  #4717

  - Fix the chat composer “phantom space” bug that appeared when backspacing CJK (and other double-width) characters after the composer got a uniform background in 43b63ccae89c….
  - Pull diff_buffers’s clear-to-end logic forward to iterate by display width, so wide graphemes are counted correctly when computing the trailing column.
  - Keep modifier-aware detection so styled cells are still flushed, and add a regression test (diff_buffers_clear_to_end_starts_after_wide_char) that covers the CJK deletion scenario.

### CODE REVIEW

**Comment by MomentDerek** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by kmk142789 — APPROVED** [review]

**Comment by joshka-oai** [comment]
@codex review

File: codex-rs/tui/src/custom_terminal.rs [hunk 1]
```diff
@@ -418,14 +418,19 @@ fn diff_buffers<'a>(a: &'a Buffer, b: &'a Buffer) -> Vec<DrawCommand<'a>> {
...
+            let width = cell.symbol().width().max(1);
+            if cell.symbol() != " " || cell.bg != bg || cell.modifier != Modifier::empty() {
+                last_nonblank = Some(col + width.saturating_sub(1));
+            }
+            col += width;
+        }
+        let x = last_nonblank.unwrap_or(0);
         last_nonblank_column[y as usize] = x as u16;
-        if x < (a.area.width as usize).saturating_sub(1) {
+        if x + 1 < row.len() {
```
Comment (joshka-oai) [inline codex-rs/tui/src/custom_terminal.rs]: @codex can you summarize this change and how it fixes the problems mentioned.

**Comment by momentsekai** [comment]
try again ci

**Comment by MomentDerek** [comment]
@joshka-oai Due to no remaining space in GitHub Action, one of the CI services has stopped running, can you help me restart it?

**Comment by joshka-oai** [comment]
Force pushed a rebase on main and a few small tweaks to make it easier to read / understand this code going forward.

Tested that this fixes the problems rendering Chinese (https://github.com/openai/codex/issues/4717), Korean (https://github.com/openai/codex/issues/4898, https://github.com/openai/codex/issues/4870), and Japanese (https://github.com/openai/codex/issues/3260) characters correctly.

**Review by joshka-oai — APPROVED** [review]
LGTM - thanks for the PR
