### PR TITLE
Fixed symlink support for config.toml

### LINKED ISSUE #6646: Honor config.toml symlinks when creating or updating config
### What version of Codex is running?

codex-cli 0.58.0

### What subscription do you have?

API

### Which model were you using?

gpt-5-codex

### What platform is your computer?

Linux 6.6.87.2-microsoft-standard-WSL2 x86_64 x86_64 (Windows 11 host with WSL2 Ubuntu)

### What issue are you seeing?

Since updating to 0.58.0 the CLI recreates `~/.codex/config.toml` on startup/update and silently replaces my existing symlink with a regular file containing default config. This breaks my setup where the real config lives on the Windows  side and is symlinked into WSL.

### What steps can reproduce the bug?

1. On 0.57.x (or any build prior to 0.58.0) create a config on Windows and symlink it into WSL.
2. Upgrade Codex CLI to 0.58.0. Launch `codex`.
3. Inspect `ls -l ~/.codex/config.toml`. The symlink has been replaced by a regular file containing the new default config.

### What is the expected behavior?

The upgrade/startup process should respect an existing symlink (or at least prompt before removing it) so shared configs remain usable after upgrades.

### Additional information

`auth.json` symlinks survive the upgrade; only `config.toml` is rewritten. The new file always contains a `[notice]` block with `hide_gpt5_1_migration_prompt = true`. Please avoid unlinking when the target is already a symlink.

### PR DESCRIPTION
**Pull request by etraut-openai**
We already support reading from `config.toml` through a symlink, but the code was not properly handling updates to a symlinked config file. This PR generalizes safe symlink-chain resolution and atomic writes into path_utils, updating all config write paths to use the shared logic (including set_default_oss_provider, which previously didn't use the common path), and adds tests for symlink chains and cycles.

This resolves #6646.

Notes:
* Symlink cycles or resolution failures replace the top-level symlink with a real file.
* Shared config write path now handles symlinks consistently across edits, defaults, and empty-user-layer creation.

This PR was inspired by https://github.com/openai/codex/pull/9437, which was contributed by @ryoppippi

### CODE REVIEW

**Comment by etraut-openai** [comment]
@codex review

File: codex-rs/core/src/path_utils.rs [hunk 1]
```diff
@@ -8,6 +12,100 @@ pub fn normalize_for_path_comparison(path: impl AsRef<Path>) -> std::io::Result<
     Ok(normalize_for_wsl(canonical))
 }
 
+pub struct SymlinkWritePaths {
+    pub read_path: Option<PathBuf>,
+    pub write_path: PathBuf,
+}
+
+pub fn resolve_symlink_write_paths(path: &Path) -> io::Result<SymlinkWritePaths> {
```
Comment (bolinfest) [inline codex-rs/core/src/path_utils.rs:26]: Can you please add a docstring for this? It looks like it guards against cycles but has no max number of symlink resolutions?

Also, can you please add a unit test?

File: codex-rs/core/src/config/service.rs [hunk 2]
```diff
@@ -385,6 +400,13 @@ async fn create_empty_user_layer(
     ))
 }
 
+async fn write_empty_user_config(write_path: PathBuf) -> Result<(), ConfigServiceError> {
+    task::spawn_blocking(move || write_atomically(&write_path, ""))
```
Comment (bolinfest) [inline codex-rs/core/src/config/service.rs:404]: Should we make an async version of `write_atomically()` instead?

File: codex-rs/core/src/path_utils.rs [hunk 3]
```diff
@@ -8,6 +12,100 @@ pub fn normalize_for_path_comparison(path: impl AsRef<Path>) -> std::io::Result<
...
+    let parent = write_path.parent().ok_or_else(|| {
+        io::Error::new(
+            io::ErrorKind::InvalidInput,
+            format!("path {} has no parent directory", write_path.display()),
+        )
+    })?;
+    std::fs::create_dir_all(parent)?;
+    let tmp = NamedTempFile::new_in(parent)?;
+    std::fs::write(tmp.path(), contents)?;
+    tmp.persist(write_path)?;
```
Comment (bolinfest) [inline codex-rs/core/src/path_utils.rs:111]: I guess this is the real reason why this needs to be sync? It doesn't appear as though there is an async version readily available...

Incidentally, here is how the tempfile crate creates a file on UNIX:

https://github.com/Stebalien/tempfile/blob/8e5ba93488ad0a6354c19776a0cb89b95273a491/src/file/imp/unix.rs#L47-L65

File: codex-rs/core/src/path_utils.rs [hunk 4]
```diff
@@ -8,6 +12,100 @@ pub fn normalize_for_path_comparison(path: impl AsRef<Path>) -> std::io::Result<
     Ok(normalize_for_wsl(canonical))
 }
 
+pub struct SymlinkWritePaths {
```
Comment (bolinfest) [inline codex-rs/core/src/path_utils.rs:15]: This type feels a little weird to me: symlinks are relatively rare, but you get this type back even when symlinks are not involved.

Should this be an enum like:

```rust
pub enum WritePath {
  RegularFile {
    write_path: PathBuf,
  }
  Symlink {
    read_path: PathBuf,
    write_path: PathBuf,
  }
}
```

**Review by bolinfest — APPROVED** [review]
